### ISSUE TITLE
If I dispose webView I can't instance new one.

### ISSUE THREAD

**Issue by turyvc** [tuarua/WebViewANE#100]
- **Have you read the README carefully?**
Yes    
- **What version of the product are you using?**
    - What version are you using?
0.0.34
- **On what operating system?**
    - OSX, Win7, Win 8, Win10, etc?
    Win7
- **If Windows is it?**
    - 32bit or 64bit
64bit
- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?
Flash Builder
- **Which version of AIR are you using?**
    - 19,20.. etc?
26
- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
dispose webView and then create new one, for example:
		webView.dispose();	
		webView=null;
		webView = new WebViewANE(); //This crash

- **What is the expected output? What do you see instead?**
New webView
- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
Yes

My app is for multiples environments & users, each environment could have differents js to inject, so if they want to change env I have to dispose webView and create a new one, but I can't(I cant remove all js injected)

**Comment by tuarua** [comment]
From the Windows section the README
"The Cef view and processes can only be attached once to your app. Therefore only one instance can be created and used."
So don't try and dispose and recreate the ANE.

Use tabs instead. These allow you to use/create/remove multiple views.
https://github.com/tuarua/WebViewANE/blob/master/example/src/StarlingRoot.as#L283

**Comment by turyvc** [comment]
Yes I knew that, but I though that if I disposed I could have another instance.

If I want to clean all js injected, how could I do it? If I open new tab the js remains.

**Comment by tuarua** [comment]
webView.injectScript("function ovverridePrevious(){//your code}");
or to remove previous
webView.injectScript("");

then load a new tab
webView.addTab("http://newUrl");
webView.currentTab = 1;
webView.closeTab(0);

**Comment by turyvc** [comment]
webView.injectScript("");  works fine.
I didnt know that only 1 script could be injected at same time.

Thank you.
