### ISSUE TITLE
Interaction with the outside of the ANE

### ISSUE THREAD

**Issue by hferreira** [tuarua/WebViewANE#102]
I continue testing this ANE.
The purpose is to use a JS report engine inside my Flex/AIR desktop app.

I already can load the report engine and also set the report definition using the injectJS method.

Everything seems to work at a first look and 0 erros on the web console however the report viewer have a print button and a export to file button.
Both buttons don't work inside the ANE and 0 erros on the web console (they work as expected on a normal web browser).

There is any permission that I must to enabled ?

PS: I'm tessting on a macOS ?

**Comment by tuarua** [comment]
The website in question uses blob urls.
WKWebview doesn't support blob urls.
