### ISSUE TITLE
Documentation Help I suspect is what I need

### ISSUE THREAD

**Issue by GeofGenerator** [tuarua/WebViewANE#107]
- **Have you read the README carefully?** Yes
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?** 1.0.0

- **On what operating system?** OSX, Win10, iOS11, Android
    
- **If Windows is it?**64bit

- **Which IDE are you using?**Flash Builder

- **Which version of AIR are you using?** AIR 27

- **What steps will reproduce the problem?**I have imported the /example project into Flash Builder, but there are compile errors - primary are the ANE paths I believe. However, Flash Builder on my Mac running High Sierra consistently crashes when attempting to get the project properties. I am a bit lost as to how to proceed as I am fine with AS3 dev, but not ANE usage
FYI : I followed the instructions to use wget to install the dependencies (bash get_dependencies.sh)
<img width="262" alt="screen shot 2017-11-29 at 16 41 13" src="https://user-images.githubusercontent.com/14346743/33387018-2679326e-d524-11e7-9355-3af67b795be6.png">

Description	Resource	Path	Location	Type
The library /workspaces/gp14_clean/WebViewANE/native_extension/ane/CommonDependencies.ane could not be found.	WebViewANESample		line 0	Flex Problem
The library /workspaces/gp14_clean/WebViewANE/native_extension/ane/WebViewANE.ane could not be found.	WebViewANESample		line 0	Flex Problem

- **What is the expected output? What do you see instead?**Flash Builder compile errors

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?** Yes
<img width="1266" alt="screen shot 2017-11-29 at 16 35 50" src="https://user-images.githubusercontent.com/14346743/33386728-8e293892-d523-11e7-99cb-206d7b9eee3f.png">

**Comment by tuarua** [comment]
The error is simply stating that the file path isn't correct.
You just need to update it.
However, I understand from what you are saying that Flash Builder is crashing when opening certain menus.
It is common knowledge that FB is all broken on High Sierra
https://forums.adobe.com/thread/2392209

I can only recommend using a trial version of another IDE such as [IntelliJ ](https://www.jetbrains.com/idea/) until Adobe/Apple can fix the issues around High Sierra.

**Comment by GeofGenerator** [comment]
Perfect thanks - just changed the paths to the one's and all is good. Sorry for being dim!

Happy camper here as (at least for now) it means I can still use Google maps API in Adobe AIR (desktop and Android) - need to check iOS yet.

Nice work - much appreciated!
