### ISSUE TITLE
Add suport for print on macOS - Known Webkit issue

### ISSUE THREAD

**Issue by hferreira** [tuarua/WebViewANE#108]
Add suport for print on macOS.
Currrently only works on Windows.

**Comment by tuarua** [comment]
As mentioned before this functionality is missing/broken in WKWebview on OSX.
It has been raised and is still an issue for WebKit.
There's nothing I can do until it is fixed there.

https://stackoverflow.com/questions/33319295/how-does-one-print-all-wkwebview-on-and-offscreen-content-osx-and-ios

http://www.openradar.me/23649229
