### ISSUE TITLE
App Process Stuck

### ISSUE THREAD

**Issue by rodrigogermanlopez** [tuarua/WebViewANE#11]
Seems like the sub process "CefSharp.BrowserSubprocess" stays always there when I close the app.
Preventing the app to close and get stuck on the Background Processes (Task Manager)

**Comment by tuarua** [comment]
I have fixed this locally and will upload Friday along with other changes

**Comment by tuarua** [comment]
Fixed.
Added new method .shutDown()
This should be called on app exit e.g.

 ```actionscript
NativeApplication.nativeApplication.addEventListener(flash.events.Event.EXITING, onExiting);
private function onExiting(event:Event):void {
		webView.shutDown();
    }
```
