### ISSUE TITLE
Inno Setup error - Runtime Error (at XXXXX). '' is not a valid integer value.

### ISSUE THREAD

**Issue by tuarua** [tuarua/WebViewANE#110]
<img src="https://public.boxcloud.com/d/1/GAsQAmWpi7YbVh8Cy9bxyIo4zAllQSr4Q2eS9wApats4GoWckrb6Yw1tHSzaEjf0aUVA7WnOAEsqGuOnD1GWsg7XemdTIfhCSmnJCyNU4JKqrlmVpCaLqK-wOvwcJDKwmeHdk7u3b6DKJm9CvzTsr3NPN4Z9zt-1cfGlCziv9Th4wdObrQ80n9qB79ziEpQoE4B7RRtF4r83qMXD5cnNZ0IS2i526vXTKf3mrt2JmEA-aT8lW4fMqs2Z8cJEg7dNfLt4jnPR5-Wbq0LpXxAD_PXkI220VlSuVdA-3OV7Wef0LRqxhM33585Gz-B5DFm6cBX80PgLoZJsKzfpI_EnWN5p-RaGeJGK687eIzfs3IL-wDn_KMUfUEwfkKb5PfQJ9t10QcYXAUj4SYmxJ3_mnQYS_M0_Ap7aB5SIzR0e-EVIa7aN_Bis1shVcgwOOvZjk7mImo-9YOIgWGUjUc6H3b9v6FXaWeAUbuglIvk1tl1HiXck2VbSYydSU_6wlo9aPIeocYv2M87C1HHi4v3oTmUHev_7b7g0iMXf3x3T9ossokEAwTKvk6yP37va_WEpcMyz6QOIigniUsLUpIDfCvcLqXd9GCalW9XXmNEBEIxtFoSV32pqYl-yW4rcGqEX9Pl9hjLEPkgS6z2-DGTep8sIcfe3zDgWwSN_yiOW32pFsO-1EtBYelifImnpL2MnxOB5uvW9h9-ImzS5AEMC7_bSiH0cRetEGBsfP6QfjlPA2dBpKk32Kki4bCS5_7RCKG2y_n7bTrcYhMQp6EwD2NwY-kcE8WTm_aMXde9_dESNhsFjuqzYk4zzYtqUk02jkf6g6mCTWJKT9pbIa5RaRZYB81Q72OU_U9tnnpjZqWI2cvhI87fVwhryJfG_lanS1GKT4rL_kZdwlmrKgdSpiMX0UkzlNuEMgETUFGLQlVcfev1y8b0uPJja185aZLRej-ljZU9DSsQEocylwaX2y1P88idJkfKPczoOh5U0tezFel4YAD4GdTvYcsEx9FvkS6J8twFkyASD0Kkv_JGp4QQoFKnLbCEPAKvo4KVzmmthpZjUyYOYJ9CHX-DyJqNAUBlzj8Y9bRXyfObRNL-v0PuBad-TvjxPETBxrMbdWMobUN-hz9iAYO6v4HRFKeOoSdSC6OVPmhwL7sdhKRNYFA7fbU0jd8WFqvP5ALSeRtK6zdoNqlvH7NgV0mQc9uz20mgfNovuMZHDVOvFBmYGvLaQX-Dq/download"/>

**Comment by tuarua** [comment]
Inno Setup scripts are based on http://github.com/stfx/innodependencyinstaller
These periodically change to reflect Microsofts urls.
win_installer/ folder has been updated with latest
Worth trying to create a with these updated scripts.

**Comment by tuarua** [comment]
The error looks to be occurring during installation of one of the following dependencies
MSVC dist 2013
MSVC dist 2015
.NET

You may not see the error on your machine as you may already have them

**Comment by wooldridgetm** [comment]
thanks. I tried it with the new setup files & got the same error.

Curiously, one of my users reported the same error with a file named 'appName (1).exe'.  When he located a file with the name 'appName.exe', the install worked just fine.  None of these installers baked in the req'd dependencies.

**Comment by tuarua** [comment]
I am able to compile the installer and rename it (before or after) and have no issues installing/reinstalling.
And that is with Windows10 and the latest Creators Update from a few days ago.

Dependancies are not baked in. They are referenced and downloaded if needed.
The error screen you posted says "Name Setup: Installing" and "NullSoft Install System v3.0.1"
I don't know what these are?

Can you upload your setup.iss file, so I can have a look.

**Comment by wooldridgetm** [comment]
Agreed. the dependencies are not baked in...but they could be provided you put them in the dependencies folder & rename them accordingly.  What I'm getting at is that if the error is/was occurring during installation of the requisite dependencies...why did it  work on the original file for the same computer but not the new file that was recently downloaded?  It baffles me.

the error screen is the Runtime Error (at 67:606) - '' is not a valid integer.  Don't worry about the screen "Name Setup: Installing" & "NullSoft Install Systems..." - the crux is the alert dialog in front of it.

Let me try the process again.

**Comment by wooldridgetm** [comment]
getting this error now...

<img width="923" alt="dependencies_error" src="https://user-images.githubusercontent.com/13317009/33620378-b30b9362-d9b5-11e7-8b02-4a2564b11ea7.png">

here is my **setup.iss** file

[ah_install_script.txt](https://github.com/tuarua/WebViewANE/files/1532177/ah_install_script.txt)

**Comment by wooldridgetm** [comment]
ah, ok. it's b/c it doesn't 'see' folder 'MyProgramDependencies' in the same directory as my executable. Will need to adjust for that problem.

**Comment by tuarua** [comment]
That's good to hear you got the installer working reliably.
Please share the files when you get a chance. I accept contributions for sure. If you do a Pull Request or you can attach a zip with changes to this ticket.

Yes that other repo was a great help to me too. 

No problem, thanks again for the donation. Is great that AIR has the ability to be extended in such a fashion, possibilities are endless - pretty funky running Chromium inside a flash based app :)
