### ISSUE TITLE
<input type="file">  doesn't work on MacOS

### ISSUE THREAD

**Issue by dannycortesv** [tuarua/WebViewANE#111]
On the web i'm loading i have a file input working well, when embedding this on Air the file picker is not been triggered. Any idea? Thanks for this great extension :)

**Comment by tuarua** [comment]
That would need to be implemented in the Swift code.
Some things in WKWebview are automatic, some things have to be self-coded.
I will add it but it won't be done until after Christmas.

**Comment by dannycortesv** [comment]
Ok @tuarua thank you so much for your support 🥇

**Comment by tuarua** [comment]
This is now available in latest version

**Comment by tuarua** [comment]
closing assumed fixed
