### ISSUE TITLE
iOS Crash at init

### ISSUE THREAD

**Issue by pautus** [tuarua/WebViewANE#113]
Hello,

I'm trying to make the ANE work on iOS but the crash at launch. it works great on Android though.
I think i miss how to use the ios_dependencies. 
I'm with AIR 28, iPhone6.
Thanks in advance.

**Comment by tuarua** [comment]
cd into example-mobile/
in Terminal run
bash get_ios_dependencies.sh

You then need to package this folder with the app  (device for device build, simulator for simulator build)
/example-mobile/ios_dependencies/device/Frameworks

How you do this depends on the IDE you are using.

when the .ipa is produced unzip it and confirm it's structure looks similar to this.

![alt tag](https://raw.githubusercontent.com/tuarua/Swift-IOS-ANE/master/tutorial/ipa-unzipped.png)

Get this working first with the provided example project before trying to integrate into your own project.

**Comment by pautus** [comment]
Yes, i got the dependencies but have trouble to implement them. My IDE is Visual Studio Code so not working on intelliJ :/

**Comment by pautus** [comment]
ok so i'm good, i have the Frameworks embedded in the ipa like in your screenshot, but this triple size of my ipa and the app won't install anymore...

**Comment by tuarua** [comment]
You need to provide more detail than that, debug info, screenshots, error messages.
And like I said, get the example project working first.
I can't help you otherwise.

**Comment by pautus** [comment]
Ok this is now working, i had to include the frameworks folder in the adt packager like this : . -C "bin/device"
But now my ipa size is more than 100 Mo (with all these new files included), is this something that i can avoid ?

**Comment by tuarua** [comment]
If you mean **aftering unzipping** the ipa it is > 100MB that is normal.
.ipa is a zip file format which contains a .app
Just make sure you are not embedding them more than once.

The files in bin/device are the **official** Apple Swift libraries. If you build an iOS app with Swift in Xcode it produces an ipa with the same Swift files (which is most new apps now)

It's important to know that this doesn't mean a user who downloads the app from the app store downloads a file the same size as your ipa.
After you upload the ipa Apple compress/strip/thin the app

Apple say this _"The size of libswiftCore.dylib in your IPA, and the size of your IPA in general, is somewhat meaningless these days.  The new thinning features in the store will remove unnecessary content from your app when delivering to specific devices, and libswiftCore.dylib contains bitcode even if your app doesn't.  This bitcode is removed before your app is downloaded to a customer device."_

Also see the "Swift ANE" section of AIR 28 release notes which mentions the same Swift libraries.
https://helpx.adobe.com/flash-player/release-note/fp_28_air_28_release_notes.html

**Comment by pautus** [comment]
ok I see, thanks for the help. It's not very convenient to work like this since it increases considerably the size of the ipa file (for the dev, uploading, testing and stuff) but if i don't have choice, then...
