### ISSUE TITLE
dispose is not working on android

### ISSUE THREAD

**Issue by hamadasamir85** [tuarua/WebViewANE#114]
- **Have you read the README carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
Latest

- **On what operating system?**
    - Android
    

- **Which IDE are you using?**
    -Animate CC 2018

- **Which version of AIR are you using?**
    -  28

- **What steps will reproduce the problem?**
    - Tried different air sdk versions and mobile phones with different android versions

- **What is the expected output? What do you see instead?**
When calling dispose the app traces "[WebViewANE] Unloading ANE..." but the view still on

**Comment by tuarua** [comment]
This is now fixed in 1.2.0
!! Important - you should only dispose the ANE if you are finished with it completely. Do not try and init + dispose the ANE multiple times.

If you wish park it to use it again later.
```
webView.visible = false;
webView.loadHTMLString("");
```

**Comment by hamadasamir85** [comment]
it is fixed in version 1.2, thanks alot
