### ISSUE TITLE
The webview captures mobile back button and closes app

### ISSUE THREAD

**Issue by hamadasamir85** [tuarua/WebViewANE#116]
- **Have you read the README carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
1.2

- **On what operating system?**
    Android
    

- **Which IDE are you using?**
    -  Animate cc 2018

- **Which version of AIR are you using?**
    - 28

- **What steps will reproduce the problem?**
    - Tried to add the back key press event listener to the webview but it is not working

- **What is the expected output? What do you see instead?**
the native app window should listen to the back key press but instead the webview captures it and closes app on press

**Comment by tuarua** [comment]
This is now fixed in 1.3.0
