### ISSUE TITLE
loadHTMLString method doesn't work in Sample Application

### ISSUE THREAD

**Issue by subdan** [tuarua/WebViewANE#117]
- **What version are you using?**
    - 1.2.0

- **On what operating system?**
    - Win7
    
- **If Windows is it?**
    - 64bit

- **Which IDE are you using?**
    - IntelliJ

- **Which version of AIR are you using?**
    - 28

- **What steps will reproduce the problem?**
    - I opened example project in IntelliJ IDEA.
    - I uncommented `webView.loadHTMLString` lines
    - I pressed Run.

- **What is the expected output? What do you see instead?**
I expect that WebView shows rendered html string but I see YouTube page.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
Yes

**Comment by tuarua** [comment]
As CefSharp's initialization is async you need to also init with url as ""
eg
webView.init(WebViewANESample.target.stage, viewPort, "")

I will update the example to mention this

**Comment by subdan** [comment]
Thanks
