### ISSUE TITLE
[Feature request] Add ability to set HTML encoding

### ISSUE THREAD

**Issue by subdan** [tuarua/WebViewANE#118]
I want to show russian text in `loadHTMLString`. But I see broken symbols.
![screenshot_1](https://user-images.githubusercontent.com/410293/35336774-208b3224-0122-11e8-9411-cd703b017156.png)
Is it possible to change encoding of HTML text rendered by `loadHTMLString`?

I tried to set charset in HTML head but it didn't help
`<meta charset="windows-1251"> or <meta charset="utf-8">`

______
I know that CefSharp allows to set text ending:
`ChromiumWebBrowser.LoadHtml(string html, string url, Encoding encoding);`

**Comment by tuarua** [comment]
This can be done without needing to add encoding options.
.NET strings are UTF-16 so the html string needs to be converted back into UTF-8 before passing to the function.

**Comment by subdan** [comment]
I pass string in UTF-8

**Comment by tuarua** [comment]
That's ok. I know what needs to be done to fix.

**Comment by tuarua** [comment]
This is now fixed in 1.3.0

**Comment by subdan** [comment]
Thank you!
