### ISSUE TITLE
Unable to install IPA file on iOS device Error: ”ApplicationVerificationFailed‘

### ISSUE THREAD

**Issue by subdan** [tuarua/WebViewANE#119]
- **What version of the product are you using?**
    - What version are you using?
1.2.0

- **On what operating system?**
iOS

- **Which IDE are you using?**
    - IntelliJ

- **Which version of AIR are you using?**
    - 28

- **What steps will reproduce the problem?**
    - Package IPA and install it on iPhone.

- **What is the expected output? What do you see instead?**
You will see error: “Installation Error: ApplicationVerificationFailed.”
If I remove \ios_dependencies\device folder this error doesn't appear but the app crashes on start.

- **Please provide any additional information below.**
I use my own certificate, provision profile, app id.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
Yes

**Comment by tuarua** [comment]
Are you using Windows or OSX to compile ?

**Comment by subdan** [comment]
Windows

**Comment by tuarua** [comment]
I don't and won't support packaging the iOS version with Windows.
It needs to be done on a Mac.
