### ISSUE TITLE
Error reporting when using the FLEX desktop app ReferenceError: Error # 1065: Variable com.tuarua.fre :: ANEError is not defined.

### ISSUE THREAD

**Issue by gs600981** [tuarua/WebViewANE#123]
version  1.3.1

Windows is 64bit Win10

using Flash Builder

AIR 27.0

![image](https://user-images.githubusercontent.com/8640698/36627469-42bff4fa-197e-11e8-8c71-2b204f6e1225.png)

help

**Comment by tuarua** [comment]
Have you run the example project provided with the repo?

**Comment by gs600981** [comment]
But CommonDependencies.ane in your example does not support the windows platform

**Comment by tuarua** [comment]
It does support Windows. Flash Builder has a bug.
See this comment
https://github.com/tuarua/WebViewANE/issues/75#issuecomment-323971188

**Comment by tuarua** [comment]
Closing due to lack of response
