### ISSUE TITLE
iPad app crashes when using loadFileURL from within applicationStorageDirectory

### ISSUE THREAD

**Issue by MMPGreg** [tuarua/WebViewANE#124]
With an app that downloads HTML content into the app's storage directory on the iPad, a crash occurs immediately when calling 'loadFileURL' on an html file at that location. I've confirmed the URL to the file in the storage directory is correct. I've tried setting the 'allowingReadAccessTo' property to both 'File.applicationStorageDirectory.nativePath', as well as the native path of the specific directory within containing the HTML file to load. I tested also by moving my HTML content into the application root and using 'File.applicationDirectory.nativePath' for read access, which did work as expected. Compiling the HTML into the app produces the expected result, but is not a workable solution when content needs to download and reside in the storage directory.

**Comment by tuarua** [comment]
Resolved offline.
Any paths used with should use loadFileURL encodeURI()

Marking this as a bug and an enhancement, to automatically support various types of file path format
eg with or without file:// prefix
with without uri encoding

**Comment by tuarua** [comment]
This is now resolved.
There is now no need for file:// or encodeURI()

eg
`webView.loadFileURL(localHTML.nativePath, File.applicationStorageDirectory.nativePath);`
