### ISSUE TITLE
run WebViewANE/example  the page was blank (https restriction on OSX - baidu.com specific)

### ISSUE THREAD

**Issue by 1395881288** [tuarua/WebViewANE#127]
- **Have you read the README carefully?**
    yes
    
- **What version of the product are you using?**
    - What version are you using?
    1.3.2

- **On what operating system?**
    macOS High Sierra 10.13.3
    
- **If Windows is it?**
    64bit

- **Which IDE are you using?**
    IntelliJ and FlexBuilder 4.7

- **Which version of AIR are you using?**
    28.0

- **What steps will reproduce the problem?**
    I run WebViewANE/example the page was blank
    
<img width="679" alt="1" src="https://user-images.githubusercontent.com/24973451/37064494-1eef90d2-21d8-11e8-8f20-7d9774b50c5f.png">

    when i open a picture it can show
<img width="858" alt="2" src="https://user-images.githubusercontent.com/24973451/37064407-cf729fea-21d7-11e8-9c36-7ecd6f550b71.png">

**Comment by 1395881288** [comment]
<img width="895" alt="3" src="https://user-images.githubusercontent.com/24973451/37081723-53864e4c-2225-11e8-803f-39213933bd0e.png">

**Comment by tuarua** [comment]
That error means you need to use http**s** urls
eg 
https://www.baidu.com

see
https://github.com/tuarua/WebViewANE/issues/97

https://stackoverflow.com/questions/32631184/the-resource-could-not-be-loaded-because-the-app-transport-security-policy-requi

**Comment by tuarua** [comment]
I investigated more.
baidu.com doesn't work properly with WKWebview.
when I go to https://www.baidu.com it redirects to **http**://

Here is the fix

`settings.userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6";`

**Comment by 1395881288** [comment]
I added "settings.userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6",  it works very well,thank you.
<img width="566" alt="1" src="https://user-images.githubusercontent.com/24973451/37185734-c2551e40-237c-11e8-8935-47f925db00e4.png">
