### ISSUE TITLE
Error: Object reference not set to an instance of an object when get getter tabDetails is used

### ISSUE THREAD

**Issue by barnabeus** [tuarua/WebViewANE#128]
- **Have you read the README carefully?**
    Yes
    
- **What version of the product are you using?**
    - What version are you using?
     1.3.2, latest release of CEF from release tag

- **On what operating system?**
    Win10 x64

- **Which IDE are you using?**
    Flash Builder

- **Which version of AIR are you using?**
    SDK 28

- **What steps will reproduce the problem?**
   1. init WebView according to examples, load https://google.com for example
   2. try to get tabDetails via code:
![image](https://user-images.githubusercontent.com/2066989/37235637-7cdd04a2-2400-11e8-926f-1c4bc0b12d47.png)

Exception returned:
Error: Object reference not set to an instance of an object.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.tuarua::WebViewANE/get tabDetails()[D:\dev\flash\WebViewANE\native_extension\src\com\tuarua\WebViewANE.as:726]
	at Project_1/onPropertyChange()[D:\Project_1_sdk_28\Projekt\src\Project_1.as:1426]
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at com.tuarua::WebViewANE/gotEvent()[D:\dev\flash\WebViewANE\native_extension\src\com\tuarua\WebViewANE.as:146]

--------
I tried to get it on different stages:
- right after init
- during event like isLoading
- after the loadFileURL
- tried init with empty string ( like the example) and using addTab(url)

The file and scripts loads fine, its just that this getter is not working and I can't access current tab URL. What could be the issue?

Attached VERBOSE debug.log from CEF too.

[debug.log](https://github.com/tuarua/WebViewANE/files/1798851/debug.log)

**Comment by tuarua** [comment]
Thanks for the detailed report.
This is a bug. I was also made aware of this yesterday by an other user. I am working on a fix and it will be fixed in next version (in next few days)

**Comment by barnabeus** [comment]
Perfect :) Umm any previous releases are free of this bug? I need at least a release supporting SDK 28, want to test some of its functionalities tomorrow. I see SDK 28 was supported since 1.1.0. So the question is when did you remove deprecated .url .title properties? I guess 1.0.0, but maybe Im lucky and it was post 1.1.0 💃 ?

**Comment by tuarua** [comment]
I added tabs in version 0.0.25. So it could be anywhere after that.
The AIR version is not that important for Windows version. The ANE is backward compatible with AIR.
The next version will have it's example compiled to AIR 29 but will work with 28,27,26 etc

**Comment by barnabeus** [comment]
"The ANE is backward/forward compatible with AIR."

Ahh yes, that's true. It just went out smoothly when i reverted the files. I misunderstood the notice when I was exporting release build in Flash Builder. It was something around "ANE not working with this SDK version" thing. Or it was already too late for me :D Either way, I can test SDK 28 features with pre v1 of your ANE. Thanks again for a great work. I will look forward to 1.4.0 now :)

**Comment by tuarua** [comment]
1.4.0 was released today.
Issue should be fixed

**Comment by barnabeus** [comment]
Thanks for the info. I will test it today or tomorrow and let you know, so you can close the issue :)

**Comment by barnabeus** [comment]
Question:
Since 0.0.33 these MS libraries were also updated, or they are the same for newer versions:
![image](https://user-images.githubusercontent.com/2066989/37285942-d80f8b04-2600-11e8-8df5-0db924756441.png)

**Comment by tuarua** [comment]
The MS libraries (.NET version and C++ 2013 and 2015) are the same
