### ISSUE TITLE
Problems with WebView inside mx:TabNavigator

### ISSUE THREAD

**Issue by Nisaba** [tuarua/WebViewANE#130]
- **What version of the product are you using?**
    - What version are you using?
1.4.0

- **On what operating system?**
Win10 64 bits
    
- **Which IDE are you using?**
    Moonshine

- **Which version of AIR are you using?**
    23

- **What steps will reproduce the problem?**
I want to use WebviewAne inside an application with Flex tabs (s:NavigatorContent  in mx:TabNavigator container).
It works fine, but when I change tab, the web page remains on the new tab and hides tab content.
If I use dispose(), the web page content disappears, but the grey background remains...

**Comment by tuarua** [comment]
The webview is not a Sprite or a Flex control. It is a native child window attached to the AIR window and runs a separate chromium process.
Use webView.visible = true / false to show / hide as needed.
Only call .dispose when completely finished with it - you can't reinitialise the ANE.
