### ISSUE TITLE
Microsoft Modern WebView (Edge) in Win32 in future update

### ISSUE THREAD

**Issue by tuarua** [tuarua/WebViewANE#132]
Microsoft have announced that a future Windows update will include an Edge based Win32 control to replace the old IE11 based control. 

https://youtu.be/D6YAJxFsmuM?t=277

This ticket is to track updates and investigate ability to choose this control or existing CEF browser.

Possible Benefits
- mp4:  H.264 + AAC support
- Assume smaller package size
- Edge is more performant

**Comment by tuarua** [comment]
Updates:
https://github.com/Microsoft/WindowsCommunityToolkit/blob/rel/3.0.0-preview/docs/controls/WebView.md

https://blogs.windows.com/msedgedev/2018/05/09/modern-webview-winforms-wpf-apps/#hUtBcfx0XGdOML6E.97

**Comment by fobrs** [comment]
[https://github.com/rjmurillo/webview-samples](url)

**Comment by apptouch** [comment]
Just starting my ramp up on using Edge over CEF.  Any links that point to using the Edge webView in a C++, Win32 app?  Thanks!

**Comment by apptouch** [comment]
Actually, I'm reviewing this now...  might be helpful someone:

https://github.com/rjmurillo/webview-samples/tree/master/WebViewSamples.Win32

**Comment by fobrs** [comment]
I've converted the win32 cpp WRL sample to cppwinrt:
[https://github.com/fobrs/WebViewSample.Win32.cppwinrt](https://github.com/fobrs/WebViewSample.Win32.cppwinrt)

**Comment by tuarua** [comment]
1.7.0 will contain the first beta-grade support for Modern WebView (Edge)
The feature set is much lighter than the CEF based view. 

There are still many bugs and features missing from Microsoft's offering such as:
- No local File support
- No HTML string support (Crash BUG)
- No Popup support
- No Bitmap Capture
- No Print support
- No Zoom Control
- No Dev Tools
- Latest Windows 10 only

On the + side
- control dll is only 151KB (compared to CEF's 80MB)
- H.264 is supported

**Comment by fobrs** [comment]
You  can use [WebView.CapturePreviewToStreamAsync()](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.capturepreviewtostreamasync) to capture a bitmap of the WebView and get a Stream for it.<br/><br/>

Use [WebViewControl.Scale](https://docs.microsoft.com/en-us/uwp/api/windows.web.ui.interop.webviewcontrol.scale) to set the zoom.<br/><br/>

Use  [WebView.NavigateToString](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.navigatetostring) to display a html string

**Comment by tuarua** [comment]
@fobrs The first 2 have NOT been implemented yet in the Win32 control.
NavigateToString causes a crash.

Please consider this issue is here for me to inform my users what to expect in the upcoming release of my project. This is not a forum.

**Comment by tuarua** [comment]
Investigate new version 4.0.0 to see what additional APIs are available

**Comment by tuarua** [comment]
Version 1.9.0 will include the following additions:

- Update to Windows Toolkit 4.0.0 for Modern WebView (Edge)
- Add local file support for Modern WebView (Edge)
- Add JS support for Modern WebView (Edge)
- Add Whitelist Blacklist support for Modern WebView (Edge)

**Comment by ArgusMagnus** [comment]
Be careful when using the Edge WebView:
https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/83
