### ISSUE TITLE
WARNING: WebViewANE: capture is Windows, iOS, Android only at the moment 

### ISSUE THREAD

**Issue by coxfrederic** [tuarua/WebViewANE#134]
I do not see any open issue for adding the capture function on MacOSX. Is this something that is still on the TODO list? Any details on this feature (or something we can help with?).

Thanks for the info

**Comment by tuarua** [comment]
Good news
This recently was added to WKWebview in OSX 10.13.
Bad news 
It uses an asynchronous callback - so that means having to rewrite the Win, Android and iOS version to also use asynchronous calls and to change the API.
Is still on the TODO list.

**Comment by tuarua** [comment]
now part of 1.6.0
