### ISSUE TITLE
Error #3500: The extension context does not have a method with the name isSupported.

### ISSUE THREAD

**Issue by coxfrederic** [tuarua/WebViewANE#135]
- **Have you read the README carefully?**
    - Follow the instructions provided before raising an issue.

Yes

- **What version of the product are you using?**
    - What version are you using?
e.g. 0.0.27

1.5.0

- **On what operating system?**
    - OSX, Win7, Win 8, Win10, etc?

OSX building for iOS 11

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?

Flash Builder

- **Which version of AIR are you using?**
    - 19,20.. etc?

29

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.

The project exists of a library project and for desktop a desktop project, for mobile a mobile project.
The code for using the ANE is written inside the library, using the SWC version of the ANE to be able to compile. The ANE is then used in both the desktop and mobile project. For desktop CommonDependencies is added, for mobile it is omitted. The desktop project builds and runs fine on OSX. However the mobile project crashes when running on the device.

[WebViewANE] Initalizing ANE...
ArgumentError
Error #3500: The extension context does not have a method with the name isSupported.
ArgumentError: Error #3500: The extension context does not have a method with the name isSupported.
3500
[WebViewANE] ANE Not loaded properly.  Future calls will fail.
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at com.tuarua::WebViewANE/init()[D:\dev\flash\WebViewANE\native_extension\src\com\tuarua\WebViewANE.as:435]
	at components::CityfashionProductReviewTool/initializeWebview()[/Users/frederic/Desktop/Exuvis/CityFashion/cityfashionProductReviewLib/src/components/CityfashionProductReviewTool.mxml:366]

    private function initializeWebview(url:String):void{
				var viewPort:Rectangle = new Rectangle(0,46,stage.width, stage.height-70);
				webView = new WebViewANE;
				if(!stage){
					trace("ERROR STAGE");
				}
				
				webView.init(stage, viewPort, url, null, 1, 0xFFFFFF, true);
				
				//update viewport
				webView.viewPort = viewPort;
				
				if(webView && !webView.hasEventListener(WebViewEvent.ON_PROPERTY_CHANGE)) webView.addEventListener(WebViewEvent.ON_PROPERTY_CHANGE, webViewPropertyChangeHandler, false, 0, true);
				webView.visible = false;
    			}

The error is coming when the following line is executed:

    webView.init(stage, viewPort, url, null, 1, 0xFFFFFF, true);

I have added the "Frameworks" folder and can confirm it is inside the Payload/{appName}=>Show package contents folder after unzipping the .ipa.

**Comment by coxfrederic** [comment]
I am getting the same error for the desktop version now. I'm checking into it what changed there.
I changed AIR version from 27 to 29.
I changed native extensions version to 1.5.0.

**Comment by coxfrederic** [comment]
Changing to AIR 27 does not fix the problem on desktop, so I'm going to try and go back from 1.5.0 of your extension to an older version to see if that works.

**Comment by tuarua** [comment]
Anytime the ANE version changes make sure you are running the get dependencies scripts again
eg 
example/get_dependencies.sh
example-mobile/get_ios_dependencies.sh

And ensure you are using this ANE for your iOS version.
native_extension/ane/mobile/WebViewANE-mobile.ane

**Comment by coxfrederic** [comment]
OK I'll check that, version 1.4.0 is working on desktop, so the dependencies are probably not updated correctly. I'll check it further thanks for the feedback

**Comment by tuarua** [comment]
No worries, Swift version changed in 1.5.0 to 4.1 (FreSwift 2.4.0) so that's likely it - unfortunately Swift versions have to be the same, so I am trying to keep  it fixed for as long as possible.

**Comment by coxfrederic** [comment]
I was not using WebViewANE-mobile.ane for mobile, somehow I missed that. I have built with 1.4.0 and this works. So I'm closing this ticket as my problem has been resolved. I will update all dependencies before moving to 1.5.0. This project rocks, very nice work!
