### ISSUE TITLE
RegEx support for urlBlackList and urlWhiteList settings properties

### ISSUE THREAD

**Issue by coxfrederic** [tuarua/WebViewANE#137]
Enhancement request:

urlBlackList and urlWhiteList property in com.tuarua.webview.Settings currently use a simple string search as stated in the docs: "This uses a simple string match. There is no regex support."

It would be awesome if it could work with RegExp.

Thanks for looking into it!

**Comment by tuarua** [comment]
I have no plans to change this.
The matching needs to be done in the native code and I'm not writing a RegExp parser for Swift + C# + Kotlin
