### ISSUE TITLE
Possible to change CefSettings.user_data_path by command line args?

### ISSUE THREAD

**Issue by daghendrik** [tuarua/WebViewANE#141]
OS: Windows

The first time I open an URL in the WebView a folder is generated at "AppData\Local\CEF\User Data". 
I'd like to have the user data folder to be created in the app storage dir of my AIR app (File.applicationStorageDirectory.nativePath) instead.  
As there is no CefSettings.userDataPath available in WebViewANE, I tried adding the command line arg "[user-data-dir](https://peter.sh/experiments/chromium-command-line-switches/#user-data-dir)", but without any luck:

```
var kvp:Object = {};
kvp.key = "user-data-dir";
kvp.value = flash.filesystem.File.applicationStorageDirectory.nativePath.toString();
settings.cef.commandLineArgs.push(kvp);
```

Am I doing something wrong or is this unsupported? In case of the latter, would it be possible to add it as a setting to CefSettings in a future release?

**Comment by tuarua** [comment]
This is implemented in CefSharp as CefSettings.UserDataPath.
user-data-dir doesn't seem to work, you are right.
Will need to be added.

**Comment by tuarua** [comment]
This has now been added
CefSettings.userDataPath
