### ISSUE TITLE
[Need Help] SDK versions

### ISSUE THREAD

**Issue by rat-moonshine** [tuarua/WebViewANE#145]
As the description said, following are the perquisites:

- Xcode 9.3
- Xcode 9.1 for iOS Simulator
- AIR 29

I'm on El Capitan having XCode 8.0. Is the used API/codes are strictly targeted to features those comes only with XCode 9.3+, or I can build and use them with 8.0 as well?

Thanks!

**Comment by tuarua** [comment]
You can't build the ANE using Xcode 8.0 no.
If you want to use the ANE on iOS you also need 9.3

You can have multiple versions of Xcode on a single machine
Just rename it Xcode8.app, Xcode9.1
Xcode.app should be the Xcode 9.3 downloaded from developer.apple.com

**Comment by rat-moonshine** [comment]
Thanks, for confirming this. 

In my case I mainly interested to run the ane on Mac app. In current situation I may not able to upgrade to Sierra/High. 

Perhaps, I should see if downloading XCode 9+ can workable in El Capitan or not. Problem is, El Capitan also refuse to download XCode9+ from Mac App store xD

**Comment by rat-moonshine** [comment]
One question - why you're not providing a compiled ane (or am I missed from finding it)?
