### ISSUE TITLE
Supplied example runs partially on macOS El Capitan

### ISSUE THREAD

**Issue by rat-moonshine** [tuarua/WebViewANE#147]
- **Have you read the README carefully?**

Yes, I guess.
    
- **What version of the product are you using?**
    - WebViewANE.ane 1.6.1
    - CommonDependencies.ane 2.4.0

- **On what operating system?**
    - macOS El Capitan

- **Which IDE are you using?**
    - Moonshine IDE 1.11.0

- **Which version of AIR are you using?**
    - Feathers 3.4.1 AIR 29.0

- **What steps will reproduce the problem?**
    - Added both the .ane to project's settings (this IDE can run native extension on fly)
    - Added requisite .swc files to project's settings
    - Tried to "Build & Run"

- **What is the expected output? What do you see instead?**
    - The project compiled successfully with following warning and ran

> : Loading configuration file /Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Feathers_3.4.1/frameworks/air-config.xml
> : Loading configuration file /Users/devsena/Downloads/WebViewANE-master/example/obj/WebViewANESampleConfig.xml
> : /Users/devsena/Downloads/WebViewANE-master/example/src/StarlingRoot.as(92): col: 22 Warning: Function value used where type Object was expected.  Possibly the parentheses () are missing after this function reference.
> :         if (!webView.isSupported) {
> :                      ^
> : bin-debug/WebViewANESample.swf (336240 bytes)
> : (fcsh) 
> : Launching application WebViewANESample.
> : Application WebViewANESample started.
> : Project Build Successfully.

    - Upon run completion I able to see the web view in AIR simulator, but it was not loading any website except a stuck blue loading bar:

![screenshot](https://user-images.githubusercontent.com/24370870/39750102-ffc549d8-52d1-11e8-84a4-fb135588c86a.png)

Do you think this is something related to running into the said IDE, or something else I need to ensure (?)

Thanks!

**Comment by tuarua** [comment]
That just looks like the url is not loading.
Try the following:

- Try a different url

- trace out the property changes eg
`private function onPropertyChange(event:WebViewEvent):void {
trace(event.params.propertyName, event.params.value);`

- Enable dev tools > right click > Inspect > Network pane
![image](https://user-images.githubusercontent.com/12083217/39777129-a4a74ffa-52fa-11e8-8a0b-243575d1f033.png)

Other notes:
You shouldn't need to add the swc. The ANE already includes the API
The warning means Moonshine doesn't support getters and setters - which is poor.

**Comment by tuarua** [comment]
See also https://github.com/tuarua/WebViewANE/issues/127

**Comment by rat-moonshine** [comment]
In a fact Moonshine do not analyse project codes (i.e. GET/SET) but gives the compilation to the Flex compiler who returns the message whichever shows to its console. 

I able to run the extension in a non sandbox environment (able to load URL), so perhaps its something at the Moonshine side. I'm closing this issue as not relevant )
