### ISSUE TITLE
Downloading file through WebViewANE

### ISSUE THREAD

**Issue by rat-moonshine** [tuarua/WebViewANE#148]
- **Have you read the README carefully?**
    - I guess so!
    
- **What version of the product are you using?**
    - 1.6.1

- **On what operating system?**
    - macOS El Capitan

- **Which IDE are you using?**
    - Signed packaging

- **Which version of AIR are you using?**
    - Feathers 3.4.1 with AIR 29.0

- **What steps will reproduce the problem?**
    - I build the supplied project with Ant and signed Apple mac certificates
    - Project runs successfully after installation - I can able too see MKWebView with proper rendering etc.
    - I'm not sure how this suppose to work, but I can't able to download any file/image through provided context option, i.e. "Download Linked File", "Download Image" etc. on my El Capitan
    - I also tried to download attachment from my Gmail but nothing happened

Can you please advise how the downloads suppose to work with the ane? 

Thanks!

**Comment by tuarua** [comment]
Downloads are not automatic in WKWebview. It needs to be coded separately.

There are 3 tasks here

1. Remove Download options from context menu. WKWebview gives no hooks to utilise these.
2. If the mimeType of the request is unsupported by WKWebview then present saveAs dialog to user to allow download.
3. Add Settings.downloadsEnabled =true/false

N.B. Does not include blob urls. Blob urls are not supported at all in WKWebview.

**Comment by JustinProminic** [comment]
Just by curiosity, the current version is 1.6.1. Do you plan the next release 1.6.5 or 1.6.5 will come after all the middle digit release?

**Comment by tuarua** [comment]
1.6.5 will be the next release in mid-June

**Comment by tuarua** [comment]
1.6.5 is now released

**Comment by rat-moonshine** [comment]
Unfortunately, compiled .ane files not accompanied anymore with the released codes at `native_extension/ane` folder. Running the supplied `get_dependencies.sh` file also not downloads anything for me:

```
$ ./get_dependencies.sh [B
--2018-06-11 11:28:11--  https://github.com/tuarua/Swift-IOS-ANE/releases/download/2.4.0/CommonDependencies.ane?raw=true
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
ERROR: cannot verify github.com's certificate, issued by ‘CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to github.com insecurely, use `--no-check-certificate'.
--2018-06-11 11:28:12--  https://github.com/tuarua/WebViewANE/releases/download/1.6.5/WebViewANE.ane?raw=true
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
ERROR: cannot verify github.com's certificate, issued by ‘CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to github.com insecurely, use `--no-check-certificate'.
```

Can you please check?

**Comment by rat-moonshine** [comment]
I gave some tests with the newer version (thanks for a soon release). 

Can you give me some details if there was some change of ways to downloading through WebViewANE, as using "Download linked file" or "Download image" does no effect in my tests. I also couldn't able to download anything as attachment from my mailbox, either.

**Comment by tuarua** [comment]
If you are still seeing those menu items you are still referencing an old copy of the ANE.
Sort that out first.

**Comment by tuarua** [comment]
You mentioned before you were using OSX 10.11 ?

It's possible they are not being hidden as their named identifiers were only added in 10.12

https://github.com/WebKit/webkit/blob/25b1e4189b884322ce6be51f3c8d0afa98033ae4/Source/WebKit/UIProcess/API/Cocoa/WKMenuItemIdentifiersPrivate.h#L37

If that's the case then I can't hide them individually.

https://github.com/tuarua/WebViewANE/blob/af46378ebed099c1c2e21785f97b72a54291814e/native_library/apple/WebViewANE/WebViewANE/WebViewVC.swift#L63

Are you able to disable the context completely using:

````actionscript
settings.contextMenu.enabled = false;
````

**Comment by rat-moonshine** [comment]
Yes, you're right, I'm on macOS 10.11.

I was using the Feathers 'example' project supplied within the source, and have set `settings.contextMenu.enabled=false` after you suggested in StarlingRoot.as. But that didn't hide the (above) context menu from showing.

Further question on this, 

1. Is downloading through WebViewANE is suppose to work if macOS >= 10.12 ?
2. If above is true, then the new fix against downloading may not work if macOS < 10.12 ?

Thanks!

**Comment by tuarua** [comment]
- Downloading works >= 10.12
- I didn't apply a "fix". I implemented the Cocoa delegates supplied by Apple. As per the webkit source, these don't look to be available for 10.11

I am only able to implement what the native control allows me.

Marking as done.

**Comment by JustinProminic** [comment]
Thank you @tuarua , for your hard work. We've tested this on OSX 10.12 and this worked. Is it possible to have some UI notification until the download completes (?)

Thanks!

**Comment by rat-moonshine** [comment]
Thank you @tuarua  , for your hard work. We've tested this on OSX 10.12 and it worked. Is it possible to have some UI notification until the download completes (?)

Thanks!

**Comment by tuarua** [comment]
You can listen to the relevant events. You would build your own ui based on these.

```
webView.addEventListener(WebViewEvent.ON_DOWNLOAD_PROGRESS, onDownloadProgress);
webView.addEventListener(WebViewEvent.ON_DOWNLOAD_COMPLETE, onDownloadComplete);

private static function onDownloadComplete(event:WebViewEvent):void {
    trace(event.params, "complete");
}

private static function onDownloadProgress(event:WebViewEvent):void {
    var progress:DownloadProgress = event.params as DownloadProgress;
    trace("progress.id", progress.id);
    trace("progress.url", progress.url);
    trace("progress.percent", progress.percent);
    trace("progress.speed", progress.speed);
    trace("progress.bytesLoaded", progress.bytesLoaded);
    trace("progress.bytesTotal", progress.bytesTotal);
}
```
