### ISSUE TITLE
Cross Origin request

### ISSUE THREAD

**Issue by ViktorLajos** [tuarua/WebViewANE#150]
On macOS, I would like to load files from my local file system, but it can't work because of the cross origin issue. I added this to the Configuration.swift:
```
if let allowFileAccessFromFileURLs: Bool = settingsWK["allowFileAccessFromFileURLs"] as? Bool {
                self.preferences.setValue(allowFileAccessFromFileURLs, forKey: "allowFileAccessFromFileURLs")
            }
```

and the 

> allowFileAccessFromFileURLs

property to the as side, and it works fine. 

With cef you can enable the cross origin request with the console, so it don't need any change.

```
			kvp = {};
			kvp.key = "allow-access-from-files";
			kvp.value = "1";
			settings.cef.commandLineArgs.push(kvp);
			
			kvp = {};
			kvp.key = "allow-universal-access-from-files";
			kvp.value = "1";
			settings.cef.commandLineArgs.push(kvp);
```

It would be great if you can do this modificaton!

**Comment by tuarua** [comment]
I will add settings.webkit.something to allow user to specify their own KVPs similar to CEF.

I am reluctant to add allowFileAccessFromFileURLs as it's own property. It's a private API and thus not officially supported. It may cause app rejection for example or be removed at any point by Apple.

**Comment by tuarua** [comment]
Will look like this
```
settings.webkit.custom.push({
    key: "allowFileAccessFromFileURLs",
    value: true
});
```

**Comment by tuarua** [comment]
1.6.5 is now released
