### ISSUE TITLE
WKWebView debugging

### ISSUE THREAD

**Issue by ViktorLajos** [tuarua/WebViewANE#151]
I would like to debug the WKWebView version of the ANE on my macOS, with Safari, but I can't see the application under the Develop menu. It works on other (native) application with WKWebView. Is there any trick to do this?

**Comment by tuarua** [comment]
From the asdocs

public function showDevTools():void     

- Shows the Chromium dev tools on Windows       
- **Enables Inspect Element on right click on OSX**       
- On Android use Chrome on connected computer and navigate to chrome://inspect

**Comment by ViktorLajos** [comment]
Nice, it works!
