### ISSUE TITLE
Question About ANE

### ISSUE THREAD

**Issue by dogofpavlov** [tuarua/WebViewANE#153]
Hello, thanks for creating this powerful ANE!  I'm very sorry to post this here but I'm not sure where else to best ask it. I don't have any problem using the ANE, rather I'm curious about how it functions. 

I noticed that a big requirement for the ANE is the MS C++ 2013,2015 & .Net 4.6 framework to be installed on the "users" machine.  This would be the first time an application I'm creating with AIR would alter the system files unrelated the application on the users machine.  I'm looking to build an application that will need to run in emergency service centers and I'm worried that if I use this ANE and it forces other runtimes to be installed... that they could possibly conflict with their current system and mess up other programs or operations. Like if said system required .Net 4.4 to be installed, would having this app install .Net 4.6 be a valid concern? 

I mean in no way to suggest these requirements make this ANE bad, just trying to understand it better. Thank you for your time and patience.

**Comment by tuarua** [comment]
Hi Ryan,
Thanks for using the ANE.

Some notes
.NET is backward compatible in that:
if program A was built with 4.6 and program B was built with 4.5 the user can have 4.7 installed and both programs will run OK. 
MSVC++ 2013 and MSVC++ 2015 are different - eg If I have only MSVC++ 2017 installed that doesn't suffice.
- The next version of the ANE won't require 2013 MSVC as CefSharp is dropping this requirement.

Understand that AIR desktop apps historically don't require any dependencies as desktop ANEs are scarce.
The best advice I can give is that you talk to the sysadmin of the center. They generally have a profile of what is installed as "stock".
eg Windows 10 comes with .NET 4.7 preinstalled.
MSVC and .NET are extremely common. Any program written in C++ or C# will use those .

**Comment by dogofpavlov** [comment]
Thank you for the reply Tuarua. You answered all my questions. Again thank you for your hard work and providing this ANE to help pick up the ball that Adobe is dropping.

**Comment by dogofpavlov** [comment]
Hi Tuarua, another question for you... 

all the dependencies I mentioned before are just for Windows correct? If I were to use the ANE to build a version of my app for Mac Desktop only, it wouldn't have to have these requirements correct? From some testing it seems that the default StageWebView in AIR on Windows does in fact work how I need it, but on Mac it does not, so that's why I'm considering this option. Also if I were to build for Mac, do I have to use the .dmg format or do desktop ANEs work with the .air format?

**Comment by tuarua** [comment]
As per the README these dlls are for Windows.Check the OSX section for Mac.ANEs are not supported with .air packages

**Comment by dogofpavlov** [comment]
thanks again
