### ISSUE TITLE
Crash on Windows 7

### ISSUE THREAD

**Issue by subdan** [tuarua/WebViewANE#154]
- **Have you read the README carefully?**
Yes
    
- **What version of the product are you using?**
1.6.1

- **On what operating system?**
Win7
    
- **If Windows is it?**
64bit

- **Which IDE are you using?**
IntelliJ

- **Which version of AIR are you using?**
29

- **What steps will reproduce the problem?**
Open "example" project in IntelliJ IDEA and run. It will crashes.

- **What is the expected output? What do you see instead?**
App should run

- **Please provide any additional information below.**
![screenshot_2](https://user-images.githubusercontent.com/410293/41031705-ac2d8c88-6981-11e8-88a5-8d34aa695c41.png)

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
Yes

**Comment by subdan** [comment]
![screenshot_3](https://user-images.githubusercontent.com/410293/41031768-d50be226-6981-11e8-8868-16a21d2dded6.png)

**Comment by tuarua** [comment]
You don't have C ++ 2015 Redistributable installed.
Read the README again please.

**Comment by subdan** [comment]
I tried to install C ++ 2015 Redistributable but installer says that I have 2017 version and I can't install 2015 version.

**Comment by tuarua** [comment]
What is the error in the screenshot? I don't speak Russian

**Comment by subdan** [comment]
Adobe Air Debug Launcher has stopped working

**Comment by tuarua** [comment]
I see you copied the dlls into bin-debug 

Did you also copy them into your AIR SDK bin folder ?
They need to sit where adl.exe is run from.

eg
C:\AIRSDK\bin\

_Unzip the contents of cef_binaries_x86.zip into the **bin folder of your AIRSDK**.
Copy the contents of the "cef_sharp_libs_x86" folder into the **bin folder of your AIRSDK**._

**Comment by subdan** [comment]
Yes, I did.

**Comment by tuarua** [comment]
Please provide a meaningful error log. 
You can use Event Viewer on Windows 7
https://www.cyberlink.com/support/faq-content.do?id=10449

**Comment by subdan** [comment]
Ok. I will make it tomorrow.

**Comment by subdan** [comment]
adl.exe
.NET Runtime
System.IO.FileNotFoundException
<Module>.FreSharpBridge.InitController()
<Module>.TRWV_contextInitializer(Void*, Byte*, Void*, UInt32*, FRENamedFunction_**)

**Comment by subdan** [comment]
I've fixed the issue by re-copying all files to AIRSDK bin foler
