### ISSUE TITLE
€ euro character is not properly encoded from JS->AS

### ISSUE THREAD

**Issue by etriceur** [tuarua/WebViewANE#155]
I know that  #125 has solved many UTF-8 encoding issues but i'm still facing the issue with € character. 
I'm using version 1.6.1 of your windows ane version.

You can easily test it  by modifying the WebViewANESample project and append the '€' character to the second parameter sent from button 1 hit ('Call Actionscript with Callback').

Is there any workaround?
Thanks

**Comment by tuarua** [comment]
There is an issue in CEF passing from JS -> C# in UTF-8

Workaround:
Use encodeURI in JS
`'args': [1, encodeURI('I am a string€'), false]`

and then in decodeURI AS
`decodeURI(paramB)`

In future please use the issue template provided. I wrote it for a reason.

**Comment by etriceur** [comment]
Thanks this is working great

**Comment by tuarua** [comment]
With the latest version (1.7.0) you don't need to apply this workaround.
I was using ANSI instead of UTF-8 in one section which I have now changed.
