### ISSUE TITLE
Load a PDF

### ISSUE THREAD

**Issue by coxfrederic** [tuarua/WebViewANE#157]
I searched the docs and issues in Github but can't find an answer.

Is it possible to load a PDF from local disk? pathFile.nativePath points to a PDF that is being loaded but not displayed it seems.

I use

`webView = new WebViewANE;
					var settings:Settings = new Settings;
					settings.webkit.plugInsEnabled = true;
					var thisL:Point = new Point(0,0);
					var thisG:Point = localToGlobal(thisL);
					var webViewViewport:Rectangle = new Rectangle(thisG.x + 10, thisG.y + 10, this.width - 45, this.height - 20);
					webView.init(stage, webViewViewport, "", null, 1, 0xFFFFFF, true);
					webView.loadFileURL(pathFile.nativePath, File.applicationStorageDirectory.nativePath);`

Is this not supported or am I using it wrong?

**Comment by tuarua** [comment]
Use the issue template

**Comment by coxfrederic** [comment]
https://github.com/tuarua/WebViewANE/issues/158
