### ISSUE TITLE
Load a PDF

### ISSUE THREAD

**Issue by coxfrederic** [tuarua/WebViewANE#158]
Answer the below. **DO NOT DELETE!!**

- **Have you read the README carefully?**
    - Follow the instructions provided before raising an issue.
    
Yes

- **What version of the product are you using?**
    - What version are you using?
e.g. 0.0.27

1.5.0

- **On what operating system?**
    - OSX, Win7, Win 8, Win10, etc?

OSX    

- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit or 64bit

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?

Flash Builder

- **Which version of AIR are you using?**
    - 29,30.. etc?

20

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.

I searched the docs and issues in Github but can't find an answer.

Is it possible to load a PDF from local disk? pathFile.nativePath points to a PDF that is being loaded but not displayed it seems.

I use

webView = new WebViewANE; var settings:Settings = new Settings; settings.webkit.plugInsEnabled = true; var thisL:Point = new Point(0,0); var thisG:Point = localToGlobal(thisL); var webViewViewport:Rectangle = new Rectangle(thisG.x + 10, thisG.y + 10, this.width - 45, this.height - 20); webView.init(stage, webViewViewport, "", null, 1, 0xFFFFFF, true); webView.loadFileURL(pathFile.nativePath, File.applicationStorageDirectory.nativePath);

Is this not supported or am I using it wrong?

- **What is the expected output? What do you see instead?**

A PDF to be displayed, I'm not seeing the PDF

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**

Not relevant

**Comment by tuarua** [comment]
It is possible
Here I've loaded the air release notes from a local fie.

![image](https://user-images.githubusercontent.com/12083217/41254129-6e459a90-6dba-11e8-8682-92c7fffcd195.png)

**Comment by coxfrederic** [comment]
Do you gave Acrobat DC installed? For me it is not working if I do it like this:

`webView = new WebViewANE;
					var settings:Settings = new Settings;
					var thisL:Point = new Point(0,0);
					var thisG:Point = localToGlobal(thisL);
					var webViewViewport:Rectangle = new Rectangle(thisG.x + 10, thisG.y + 10, this.width - 45, this.height - 20);
					webView.init(stage, webViewViewport, "", null, 1, 0xFFFFFF, true);
					webView.loadFileURL(pathFile.nativePath, File.applicationStorageDirectory.nativePath);`

**Comment by coxfrederic** [comment]
I found a workaround by upgrading to 1.6.5 and then using PDF.js viewer together with https://github.com/tuarua/WebViewANE/issues/150

So I have a solution but unclear why the code is not working directly to the PDF.
