### ISSUE TITLE
App does not start on Win7/10 but works just fine on macOS.

### ISSUE THREAD

**Issue by alwinlubbers** [tuarua/WebViewANE#162]
- **Have you read the README carefully?**
    - Yes.
    
- **What version of the product are you using?**
    - 1.7.0

- **On what operating system?**
    - Windows 7 and 10
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit

- **Which IDE are you using?**
    - Animate CC 2018

- **Which version of AIR are you using?**
    - AIR 26.0

- **Please provide any additional information below.**
    - Animate CC Output:

> [SWF] com.tuarua.WebViewANE - 30530 bytes after decompression
> [SWF] BusinessBoard.swf - 5505735 bytes after decompression
> [CommonDependencies] Initalizing ANE...
> [WebViewANE] Initalizing ANE...

10-15 seconds later....
> Test Movie terminated.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
- I haven't tried this, but my app does nothing different from the sample.

I've tested my app on Windows 7, Windows 10 and macOS High Sierra. It works just fine on macOS but it does not even launch (i don't see my app, but its trying to do stuff in the background) on Windows. I've downloaded and installed all the required tools. (C++ 2015 and .Net 4.5). All the libraries are in the same folder als the main exe.

Thanks in advance. 

Code snippet:
```
import com.greensock.*;
import com.greensock.easing.*;
import com.tuarua.CommonDependencies;
import com.tuarua.WebViewANE;
import com.tuarua.utils.os;
import com.tuarua.webview.ActionscriptCallback;
import com.tuarua.webview.DownloadProgress;
import com.tuarua.webview.JavascriptResult;
import com.tuarua.webview.LogSeverity;
import com.tuarua.webview.Settings;
import com.tuarua.webview.WebViewEvent;
import com.tuarua.webview.popup.Behaviour;
import com.tuarua.webview.popup.Popup;
import flash.display.BitmapData;
import flash.utils.Timer;
import flash.filters.*;

stop();

var commonDependenciesANE:CommonDependencies = new CommonDependencies();
var webview:WebViewANE = new WebViewANE();
var viewport:Rectangle = new Rectangle(0, 0, 100, 100);
var settings:Settings = new Settings();
var webvBM:Bitmap;
var failedToLoad:Boolean = false;
var musicaNotifiActive:Boolean = false;
var showBrowserTimer:Timer;
var curURL:String;
var curTitle:String;
var omniBoxShowing:Boolean = false;
var browserIsBitmap:Boolean = false;


var TFLeft:TextFormat = new TextFormat();
	TFLeft.align = TextFormatAlign.LEFT;
	
var TFCente:TextFormat = new TextFormat();
	TFCente.align = TextFormatAlign.CENTER;


webview.addEventListener(WebViewEvent.ON_PROPERTY_CHANGE, onPropertyChange);
webview.addEventListener(WebViewEvent.ON_FAIL, onFail);
webview.addEventListener(WebViewEvent.ON_PERMISSION_RESULT, onPermissionResult);
webview.addEventListener(WebViewEvent.ON_URL_BLOCKED, onUrlBlocked);
webview.addEventListener(WebViewEvent.ON_POPUP_BLOCKED, onPopupBlocked);

settings.popup.behaviour = 0;
settings.webkit.allowsAirPlayForMediaPlayback = false;
settings.webkit.plugInsEnabled = false;
settings.cacheEnabled = false;
settings.userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7";
adrOverlay.alpha = 0;

function resizeEvent(animSeconds:Number = 1):void {	
	if(webview.isInited != true) {
		webview.init(stage, viewport, "about:blank", settings, 1, 0xFFF1F1F1, true);
		webview.load(MovieClip(root).homepageUrl);
	}
}

//There is more code below, but it has nothing to do with the ANE.
//The resizeEvent(); gets called when the user leaves the 'login'-screen in my app.
//The code is placed inside an MovieClip on the root stage.
	
```

The problem occurs in Test mode, debug mode and the compiled app.

-Alwin

**Comment by tuarua** [comment]
Did you mean .NET 4.6? The ANE requires 4.6 or >
To retrieve the error open Event Viewer > Windows Logs > Application and look for the error
A screenshot of your final package files would be useful.
A launch crash like this is 99% of time related to the cef and c# files, or .NET version

**Comment by alwinlubbers** [comment]
![img_7419](https://user-images.githubusercontent.com/31679714/42734588-d1865d46-8846-11e8-9207-da761ab898ad.jpg)
![img_7420](https://user-images.githubusercontent.com/31679714/42734589-d19fee64-8846-11e8-8fc5-f1449f9f0514.jpg)

The first image shows the root directory of my Adobe Air app.
The second image shows the "Add/remove program" list in Control Panel.

Sorry for the bad image quality, that's because the computer is on a private network with no acces to the internet. (The app also does not launch when connected to internet).

Thanks in advance.
-Alwin

**Comment by tuarua** [comment]
Your files look correct.
I have remembered that .NET **4.6.2** is needed for latest version (I forgot to update the wiki)
https://www.microsoft.com/en-us/download/details.aspx?id=53344

Please confirm the actual crash error: open Event Viewer > Windows Logs > Application and look for the error

**Comment by alwinlubbers** [comment]
Hi,
Thanks for the quick reply.

I am now installing .NET 4.6.2.

I don't see my Application anywhere in the Event Logger.

Thanks.

-Alwin

**Comment by tuarua** [comment]
Please build a very simple app (a reduced test case) based on https://github.com/tuarua/WebViewANE/blob/master/example-desktop-as3/src/WebViewExampleAS3.as#L12 and test that 

You are not using the same code as I.
This is wrong for example
```
webview.init(stage, viewport, "about:blank", settings, 1, 0xFFF1F1F1, true);
webview.load(MovieClip(root).homepageUrl);
```
it should be 
```
webview.init(stage, viewport, MovieClip(root).homepageUrl, settings, 1, 0xFFF1F1F1, true);
webview.visible = true;
```

I can't debug without an error message.

It's unclear from your description and the fact you say there is no error in Event Viewer whether the app is crashing or not.

All examples on my machines are working correctly.

**Comment by alwinlubbers** [comment]
Hi,

I've tried making an blank app with only these few lines of code:

```
import com.tuarua.CommonDependencies;
import com.tuarua.WebViewANE;
import com.tuarua.utils.os;
import com.tuarua.webview.ActionscriptCallback;
import com.tuarua.webview.DownloadProgress;
import com.tuarua.webview.JavascriptResult;
import com.tuarua.webview.LogSeverity;
import com.tuarua.webview.Settings;
import com.tuarua.webview.WebViewEvent;
import com.tuarua.webview.popup.Behaviour;
import com.tuarua.webview.popup.Popup;
import flash.display.BitmapData;
import flash.utils.Timer;
import flash.filters.*;

stop();

var commonDependenciesANE:CommonDependencies = new CommonDependencies();
var webview:WebViewANE = new WebViewANE();
var viewport:Rectangle = new Rectangle(0, 0, 100, 100);
var settings:Settings = new Settings();


settings.popup.behaviour = 0;
settings.webkit.allowsAirPlayForMediaPlayback = false;
settings.webkit.plugInsEnabled = false;
settings.cacheEnabled = false;
settings.userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7";

webview.init(stage, viewport, "http://www.google.com", settings, 1, 0xFFF1F1F1, true);
webview.visible = true;
```

But it still does not work. I'm now downloading the AIR30 SDK and i will give that a shot.

**Comment by alwinlubbers** [comment]
Hi,

Now i'm getting an Windows Error Report, and the app also shows up in the Error Log.

I've made an simple app with these lines of code:

```
import com.tuarua.CommonDependencies;
import com.tuarua.WebViewANE;
import com.tuarua.utils.os;
import com.tuarua.webview.ActionscriptCallback;
import com.tuarua.webview.DownloadProgress;
import com.tuarua.webview.JavascriptResult;
import com.tuarua.webview.LogSeverity;
import com.tuarua.webview.Settings;
import com.tuarua.webview.WebViewEvent;
import com.tuarua.webview.popup.Behaviour;
import com.tuarua.webview.popup.Popup;
import flash.display.BitmapData;
import flash.utils.Timer;
import flash.filters.*;

stop();


var commonDependenciesANE:CommonDependencies = new CommonDependencies();
var webview:WebViewANE = new WebViewANE();
var viewport:Rectangle = new Rectangle(0, 0, 1280, 720);
var settings:Settings = new Settings();



addEventListener(Event.ENTER_FRAME, fl_EnterFrameHandler);

function fl_EnterFrameHandler(event:Event):void
{
	removeEventListener(Event.ENTER_FRAME, fl_EnterFrameHandler);
	webview.init(stage, viewport, "https://www.google.com", null, 1, 0xFFF1F1F1, true);
	webview.visible = true;
	
}

```


I'm getting 3 error's.

![knipsel](https://user-images.githubusercontent.com/31679714/42738766-a84cc2f6-8889-11e8-9b57-2a9e16c786f9.PNG)
![2](https://user-images.githubusercontent.com/31679714/42738768-ac4de84e-8889-11e8-8cfe-4200b6945011.PNG)
![3](https://user-images.githubusercontent.com/31679714/42738769-aed5026e-8889-11e8-980b-4a1092bd0b47.PNG)


Thanks.
Alwin

**Comment by alwinlubbers** [comment]
Any idea?

**Comment by tuarua** [comment]
Something strange happened with the upload of WebViewANE.ane

**Comment by tuarua** [comment]
If all is working for you can the ticket be closed?
