### ISSUE TITLE
My operating system is Win10,  is webviewane support flash ?

### ISSUE THREAD

**Issue by 1395881288** [tuarua/WebViewANE#164]
My operating system is Win10,  is webviewane support flash ?
thanks.

**Comment by 1395881288** [comment]
![1](https://user-images.githubusercontent.com/24973451/43260337-c6364e6a-910b-11e8-94fb-ef55f738d433.jpg)

**Comment by tuarua** [comment]
Yes.
1) You need to install the PPAPI version of Flash Player for Chromium.
https://get.adobe.com/flashplayer/otherversions/
or
2) reference a local version of the plugin
```
settings.cef.commandLineArgs.push({
            key: "ppapi-flash-path",
            value: "C:\\path\\to\\pepflashplayer.dll"
        });

        settings.cef.commandLineArgs.push({
            key: "ppapi-flash-version",
            value: "30.0.0.000"
        });
```

**Comment by 1395881288** [comment]
thanks  ，You are a genius。
