### ISSUE TITLE
How can I return the result of actionscript function into javascript function without using callJavascriptFunction?

### ISSUE THREAD

**Issue by jsrdzhk** [tuarua/WebViewANE#173]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    yes
- **What version of the product are you using?**
    - What version are you using?
  1.8.1

- **On what operating system?**
  win7
    
- **If Windows is the AIR app **32bit** or **64bit**?
   32bit

- **Which IDE are you using?**
    Flash Develop

- **Which version of AIR are you using?**
    30

Hi!Thanks for maintaining WebViewANE.I'm new to this lib and I want to know if there is a way that I can return the result of actionscript function into the javascript so that javascript can use the result to do something.I have seen the doc and found a solution using callJavascriptFunction to pass the as3 result to the javascrpit and do some work with the result.Can you tell me another solution.Thanks a lot!

**Comment by tuarua** [comment]
Synchronous calls are not possible.
Please See https://github.com/tuarua/WebViewANE/issues/152

**Comment by jsrdzhk** [comment]
@tuarua I'm sorry but I still have a question.My project use the lib [and](http://apdevblog.com/aswing-actionscript-ui-components/) and I write an class named WebPageFrame which extends the JFrame class.In this class,I append the JPanel instance named htmlPanel into the JFrame and I create one webviewane instance with htmlPanel.stage as the second parameter of the function init().I found when I execute the dispose() function of the instance of WebViewANE,there was a blank block on the screen where the viewport was set and the content was blocked by the blank block.And when I create the instance of WebViewANE again,my app crashed.I debugged the program and I found it crashed at the init() function of WebViewANE.My problem might be a little stupid but I could't solve it.Please give me some suggestions.Thanks a lot!

**Comment by jsrdzhk** [comment]
@tuarua I solved it by just creating one instance of WebViewANE and dispose it after the whole app exit.When i need to open another webview,I just hide the instance of WebViewANE and show it after another load() function.Next work is to add some control to move the webview by the mouse-down event and hide the webview by mouse-click the close control.Is there any easy way to finish this target by WebViewANE?Thanks for your help!
