### ISSUE TITLE
Question about load() and evaluateJavascript()

### ISSUE THREAD

**Issue by jsrdzhk** [tuarua/WebViewANE#175]
- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    yes
- **What version of the product are you using?**
    - What version are you using?
   1.8.1

- **On what operating system?**
    win7
    
- **If Windows is the AIR app **32bit** or **64bit**?
    32bit

- **Which IDE are you using?**
    Flash Develop

- **Which version of AIR are you using?**
    30

Hi, @tuarua ！Thanks for watching my question.I use some code below to try to adjust the size of the viewport of WebViewANE.Here webview is the instance of WebViewANE and has been initialized by init().
```actionscript
webview.load(urlToLoad);
webview.evaluateJavascript("document.body.scrollWidth",onSetWebPageWidth);

private function onSetWebPageWidth(jsResult:JavascriptResult):void{
       var width:uint=jsResult as uint;
       webview.viewport=new Rectangle(50,100,width,750);
 }
```
However,the size of web page only adjust sometimes.I guess the evaluateJavascript() function was invoked before the whole work of load() function finished.Can you tell me what caused this situation? Or tell me another way to modify the size of webview to make its width equal to the width of html body,please.Thanks a lot!

**Comment by tuarua** [comment]
load is asynchronous, you need to write your code taking this into consideration.
As I mention in the README the issue tracker is for bugs.
