### ISSUE TITLE
I cannot find any way to modify the accept-language headers

### ISSUE THREAD

**Issue by jsrdzhk** [tuarua/WebViewANE#177]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
    1.8.1

- **On what operating system?**
    Win7
    
- **If Windows is the AIR app **32bit** or **64bit**?
    32bit

- **Which IDE are you using?**
    Flash Develop

- **Which version of AIR are you using?**
    30

Hello,I known ISSUE is only for bugs and I am sorry to disturb you.It seems that webviewane has no way to modify the accept-language.I tried my best to find this feature but failed.Please tell me the way to  modify the accept-languages if it exists.Or please add this feature if you will.Thanks anyway!

**Comment by tuarua** [comment]
There is no way to do that.

It would require custom coding and it's not something I have a need for.
I would have to charge to add this.
If you want to discuss that then please contact info@tuarua.co.uk for a quote.

**Comment by jsrdzhk** [comment]
@tuarua I'm sorry but I have to implement this feature by myself.

**Comment by tuarua** [comment]
Your adt command is wrong. Re-use what is already there.

1. open build-windows.bat and modify the 2 paths at the top
2. In VS Open Build > Batch Build
3. Select All **except** 2 "Any CPU"

This builds the dlls, creates the ANE and copies dlls to AIR bin folder

Make sure you follow the instructions here to make the changes you need for the headers
https://github.com/cefsharp/CefSharp/issues/534#issuecomment-60694502

**Comment by jsrdzhk** [comment]
Thanks for your response!I followed your instructions and modified the accept-language by these code:
```
CefReturnValue IRequestHandler.OnBeforeResourceLoad(IWebBrowser browserControl, IBrowser bsrowser, IFrame frame,
            IRequest request, IRequestCallback callback)
        {
            var headers = request.Headers;
            headers["Accept-Language"] = "zh-CN";
            request.Headers = headers;
            return CefReturnValue.Continue;
        }
```
That successfully changed the cef's request header and the website displayed language became Chinese.I tried to improve this method so that I can specify the accept-language from as code.Here's the change:
```
CefReturnValue IRequestHandler.OnBeforeResourceLoad(IWebBrowser browserControl, IBrowser bsrowser, IFrame frame,
            IRequest request, IRequestCallback callback)
        {
            var headers = request.Headers;
            headers["Accept-Language"] = _acceptLanguage;
            request.Headers = headers;
            return CefReturnValue.Continue;
        }
```
_acceptLanguage was fetched from as code by `AcceptLanguage = settingFre.GetProp()` and I changed the contructor of `RequestHandler` into 
```
public RequestHandler(ArrayList whiteList, ArrayList blackList, string acceptLanguage) {
            _whiteList = whiteList;
            _blackList = blackList;
            _acceptLanguage = acceptLanguage;
        }
```
In the CefView.cs,I added the member variable `public string AcceptLanguage { private get; set; }`
After these changes,I found no matter how I change the property acceptLanguage in as,the accept-language request header was always zh-CN.

**Comment by tuarua** [comment]
Thanks for investigating and providing details of the changes.

I didn't know about CefSettings.AcceptLanguageList

As it is a small change I have added it to the next version [1.9.0](https://github.com/tuarua/WebViewANE/tree/1.9.0) which I will release 15/09/18

**Comment by jsrdzhk** [comment]
@tuarua I found the webview was always displayed on the top of the app and everything was covered by the webview instance.Is it possible to show some notifications by using as code?And I'm interested in the internal principle of this project.Should I start with your another project FreSharp?

**Comment by tuarua** [comment]
#1 in the wiki
https://github.com/tuarua/WebViewANE/wiki/Troubleshooting---FAQs#can-i-overlay-flash-display-objects-over-the-webview

**Comment by jsrdzhk** [comment]
@tuarua Sorry for my stupid question.I'm a novice for GitHub and I only saw the HOME page of the wiki.I thought the Wiki had only one page before reding your answer......
