### ISSUE TITLE
result of callJavascriptFunction was incorrect

### ISSUE THREAD

**Issue by jsrdzhk** [tuarua/WebViewANE#179]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
e.g. 1.8.1

- **On what operating system?**
    Win7
    
- **If Windows is the AIR app **32bit** or **64bit**?
    32bit

- **Which IDE are you using?**
    Flash Develop

- **Which version of AIR are you using?**
    21

- **What steps will reproduce the problem?**
Hi,tuarua!It seems that callJavaScriptFunction has some problems.I want to use window.confirm by callJavaScriptFunction.Here's the details:
```
webview.callJavascriptFunction("window.confirm",onConfirm,"are you sure?");
```
The callback is here:
```
public function onConfirm(jsResult:JavasciptResult){
    var isCancel:Boolean=jsResult as Boolean;
    var isCancel2:Boolean=Boolean(jsResult);
    if(isCancel){
        //do sth
    }
    //....
}
```
No matter I choose OK or Cancel on the popup javascript modal window,the result of `isCancel` is always `false` and the result of `isCancel2` is always `true`.
Another problem is when I use Chinese as the content of the confirm.The last character of displayed content is always become a strange character.And I must add a blank after my last character,or the Devtools will show the invoked javascript function has syntax error.
Thanks for reading my problem!

**Comment by tuarua** [comment]
Your onConfirm code is totally wrong.

Follow the guide properly in the wiki.
https://github.com/tuarua/WebViewANE/wiki/Javascript-Binding#example---call-javascript-function-on-page

Regarding the Chinese characters, please open a new issue with exact code to allow me to reproduce.
