### ISSUE TITLE
Failed to package AIR application

### ISSUE THREAD

**Issue by berkeley-games** [tuarua/WebViewANE#18]
```
Failed to package AIR application
Packaging failed. Packager internal error.
```
I receive this error on both Windows and OSX running off the latest master branch when trying to package application for release.

Debug works on Windows, building from either Adobe Animate CC or IntelliJ IDEA.

Debug does not work on OSX in either Animate or IntelliJ.

OSX debug build crashes with:

`adl quit unexpectedly`

**Comment by tuarua** [comment]
Hi,
which branch are you checking out from ?
master
CEF-WinForms
CEF-WPF

**Comment by tuarua** [comment]
also, how are you running. With Flash Builder, IntelliJ or using command line

**Comment by berkeley-games** [comment]
I have updated the issue. I was running the WinForms ANE on OSX before which was causing the "WebViewANE is not supported for MacOS-x86-64" error.

**Comment by tuarua** [comment]
This is usually a signing problem.
Are you self signing?
https://forums.adobe.com/thread/1568459
https://forums.adobe.com/thread/1605022

I should note that the ANEs are not signed in any way as they don't need to be.

**Comment by berkeley-games** [comment]
Using either a temporary self-signed certificate or the one I have from Thawte, I still get the Packager internal error. The certificate works fine in all of the my other projects.

Including the WebViewANE.ane extension in the project is what is causing the error. If I remove the ANE dependency, I am able to package.

**Comment by tuarua** [comment]
Are you packaging any of the cef dlls or exes ( you shouldn't be)

What version of Windows are you using 7 ? 
Another user on the Starling forum had the same error on Win 7 when building release. They resolved by rebuilding the ANE from source, which is included.

**Comment by berkeley-games** [comment]
Windows 10.

I am able to package all of the dependencies without a problem. Everything is included in the installer. If I try to include the WebViewANE extension, I get the packaging error.

[Here is the what the installer spits out](http://i.imgur.com/FlRXJnq.png) when I build without the native extension. You can see the dependencies sitting where they belong.

**Comment by tuarua** [comment]
I've looked at the screengrab.
You should backtrack to the example project I provided with the repo.
I have provided IntelliJ and Flash Builder projects.
Build a release version of this. Does it package ok. If so compare what is different.

Some things I see that are different in your project,
1) You are packaging the cef binaries, dlls etc. I don't in my project. 
2) I am using captive runtime.

I am able to package the sample project release version OK, as are many of others.
1 user on the Starling forum had a problem with Win7.

**Comment by berkeley-games** [comment]
Packaging the example project as either a captive runtime bundle or native installer fails with the same error message as my personal project. It doesn't have anything to do with including the binaries or dll files.

The example project also works as a debug build.

**Comment by berkeley-games** [comment]
Latest master branch fixed this issue.
