### ISSUE TITLE
Any way to get ANE files?

### ISSUE THREAD

**Issue by sairope** [tuarua/WebViewANE#183]
I'm having some issues with bash on Windows. Is there any other way of obtaining the ANE files for Android and iOS?

**Comment by tuarua** [comment]
Just open the file and see what it does. It's not complicated.

https://github.com/tuarua/WebViewANE/blob/master/example-mobile/get_ios_dependencies.sh
https://github.com/tuarua/WebViewANE/blob/master/example-mobile/get_android_dependencies.sh
