### ISSUE TITLE
Cannot display the browser window in a Windows10 PC 

### ISSUE THREAD

**Issue by jsrdzhk** [tuarua/WebViewANE#185]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
e.g. 1.9.0

- **On what operating system?**
    - Win10 1803
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit

- **Which IDE are you using?**
    - Flash Develop

- **Which version of AIR are you using?**
    - 31

Hello,@tuarua!Sorry for disturbing you.This greate ane works fine in almost all PCs but I found a problem in a Windows 10 PC.This PC cannot display the browser when I set the webview.visible to true.In the task manager,Cefsharp.browserSubprocess.exe is running,including gpu-process and render process.This PC has .net 4.7 and visual c++ 2017 reditributable.
I'm sure the visible property is true because my program works fine in many other PCs.I also tried your example code in this PC and it works fine.
I have been trapped in this problem for about three days and hope to hear some advices from you.Thanks for reading my problem!

**Comment by tuarua** [comment]
If the example project works fine then it will be something in your code or likely the url you are loading is not loading. You are focusing on the _visible_ aspect but if the example is working it's not a problem in the ANE. Use `showDevTools` to debug the page loading. put trace logs on events such as: WebViewEvent.ON_PROPERTY_CHANGE
WebViewEvent.ON_FAIL

Otherwise there is not a lot else I can say.
You'll need to figure it out. I can only look into actual bugs.

**Comment by tuarua** [comment]
@jsrdzhk Please provide latest details including screenshots, 
Please confirm which samples apps are working and which are not.

**Comment by jsrdzhk** [comment]
@tuarua Hello!I have encountered a new problem.In one PC,I cannot see the content of the webpage,although elements of this webpage has been all loaded.I tried to run your example in this PC but it still failed.I use FlashDevelop to compile your example.The AIR SDK version is 31.0.
I use `adl.exe -runtime ../runtimes/air/win -extdir lib/ application.xml` to run this example.
I got some error info:`DevTools listening on ws://127.0.0.1:8088/devtools/browser/8e1a27d0-d57e-4b3a-9178-fe3440a4ccc2
[1029/180902.349:ERROR:gpu_process_transport_factory.cc(1027)] Lost UI shared context.`
Here is the example's screenshot:
![1](https://user-images.githubusercontent.com/31811412/47644304-b99f1780-dba8-11e8-948d-2fcf2fada33a.PNG)
I use Ctrl+A to select all and drag the selected things,here is the screenshot:
![2](https://user-images.githubusercontent.com/31811412/47644472-329e6f00-dba9-11e8-9f8f-7b90993c8c5a.PNG)
I tried many URIs but all failed.

**Comment by jsrdzhk** [comment]
@tuarua The prevous problem is really different from the problem I committed just now.I can't see the webview.It seems like the webview is transparent.However,your example works well on that PC.So it maybe my fault.

**Comment by tuarua** [comment]
With the new problem:
What graphics card is running on the PC? 
Is "App scaling" at 100%, 125% etc ?
Can you recompile the ANE commenting out the following in MainController.cs
if (Environment.OSVersion.Version.Major > 7) {parameters.ExtendedWindowStyle = (int) WindowExStyles.WS_EX_LAYERED;parameters.UsesPerPixelTransparency = true;}

if (source.CompositionTarget != null) {source.CompositionTarget.BackgroundColor = backgroundMediaColor;}

With the first problem:
Can you try adding the following to the app-xml
<requestedDisplayResolution>high</requestedDisplayResolution><depthAndStencil>true</depthAndStencil><renderMode>direct</renderMode>

**Comment by tuarua** [comment]
Please also let me know if either of these machines are non PCs, eg if they are a mac running VirtualBox.

**Comment by jsrdzhk** [comment]
@tuarua Hello!All of these PCs are windows,not virtual machine.I recompiled the WebViewANELib.dll with your suggestion.It works fine now.Thanks!
I cannot try to solve the first problem util tomorrow.
I tried to change to CefSettings.Locale to modify the displayed language of right-click context.It works fine.The modification is the same as the AcceptLangageList you added before.Can you add this feature in the next release.I think this feature is really useful.Thanks so much!

**Comment by tuarua** [comment]
Thanks,
It's good to know where the problem comes from.
However I can't remove the code as it was added to resolve this another issue.
https://github.com/tuarua/WebViewANE/issues/168

Can you now try **reverting** the lines and change:
`source.CompositionTarget.BackgroundColor = backgroundMediaColor;`
to
`source.CompositionTarget.BackgroundColor = Colors.Transparent;`

If you can help with this issue, I will add locale in the next version.

**Comment by jsrdzhk** [comment]
@tuarua Hello!I'm willing to help with this issue but I cannot connect to this PC by teamviewer today.I will try your advice when I can connect to this PC again.

**Comment by tuarua** [comment]
Thank you

**Comment by jsrdzhk** [comment]
@tuarua Hello!
The first problem:
I have tried to add 
```
<requestedDisplayResolution>high</requestedDisplayResolution>     <depthAndStencil>true</depthAndStencil>     
<renderMode>direct</renderMode>       
```
to application.xml.However,the first problem is still not solved.

**Comment by tuarua** [comment]
Any update on testing problem 2?

**Comment by jsrdzhk** [comment]
@tuarua Hello!I have been sick for about one week and I heard from my teammate that the user of the problematic computer has resigned.I urged my teammate to find this PC as soon as possible.I will try your code if I have access to this PC.
For the first problem,do you have another solution?

**Comment by tuarua** [comment]
re: first problem - I don't know the reason for this. I am unable to reproduce.

**Comment by JanFW** [comment]
With version 2.0 `<transparent>true</transparent>` works fine!
@taurua: Many thanks for the quick update!
