### ISSUE TITLE
How to get a  transparent html body of  webview?

### ISSUE THREAD

**Issue by samchild** [tuarua/WebViewANE#186]
Hi , i want to make  the white background of browser disappear( just the html body disappear, not the elements in the body ) and get  a  transparent  webview over my as3 air object , how can i do that ?

thanks

**Comment by tuarua** [comment]
This is not possible in Desktop.
If you are talking about mobile then see the example
https://github.com/tuarua/WebViewANE/blob/master/example-mobile/assets/localTest.html#L11

In future answer the issue template questions. It clearly says 

> Answer the below. **DO NOT DELETE!!**
