### ISSUE TITLE
Error #3500: The extension context does not have a method with the name init.

### ISSUE THREAD

**Issue by fftidus** [tuarua/WebViewANE#193]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
      2.0.1

- **On what operating system?**
    - Win10,android
    
- **If Windows is the AIR app **32bit** or **64bit**?
    -  64bit

- **Which IDE are you using?**
    Flash Builder

- **Which version of AIR are you using?**
    31

webView.init(stage, viewPort, "",settings, 1, 0x00F1F1F1);

On win10,the program shut down.
On andriod ,I have got this error: Error #3500: The extension context does not have a method with the name init.

**Comment by tuarua** [comment]
Please follow the instructions in the [wiki](https://github.com/tuarua/WebViewANE/wiki)

**Comment by fftidus** [comment]
Yes I unzip "cef_binaries_x64" to AIRSDK, and used powershell to run "get_dependencies.ps1",but still have this problem...

It is too hard for me to use T_T.

Could you please provide a way that I can use it without my brain....OTZ

**Comment by tuarua** [comment]
Use cef_binaries_**x86** as per the instructions

Follow the instructions carfefully. There are no shortcuts.

https://github.com/tuarua/WebViewANE/wiki/Chromium-WebView
