### ISSUE TITLE
Touch not working in Windows 7

### ISSUE THREAD

**Issue by esidegallery** [tuarua/WebViewANE#194]
Hi @tuarua, I'm aware that testing touch in Windows is tricky, but I found this thread that seems to have a fix: https://github.com/cefsharp/CefSharp/issues/1833. Is it possible to implement into WebViewANE?

**Comment by tuarua** [comment]
I have added the code outlined in the CefSharp ticket.
I have no way of testing as I don't own a Windows 7 touch device

**Comment by esidegallery** [comment]
@tuarua, I just upgraded and tested and it worked! Thank you for doing this. 🙏
