### ISSUE TITLE
Application crashes when capturing many screenshots

### ISSUE THREAD

**Issue by etriceur** [tuarua/WebViewANE#198]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
e.g. 1.6.1

- **On what operating system?**
    - Win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit

- **Which IDE are you using?**
    - IntelliJ

- **Which version of AIR are you using?**
    - 25

- **What steps will reproduce the problem?**
- random - many many screenshots (webView.capture())

- **What is the expected output? What do you see instead?**
Application crash.
- **Please provide any additional information below.**
Windows error event logs:
 
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-01-18T16:15:46.660410900Z" /> 
  <EventRecordID>18641</EventRecordID> 
  <Channel>Application</Channel> 
  <Security /> 
  </System>
- <EventData>
  <Data>Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: 
   System.Runtime.InteropServices.ExternalException at System.Drawing.Image.RotateFlip(System.Drawing.RotateFlipType) at FRESharpCore.FRESharpCLR.getFREObject(System.Drawing.Bitmap, FRESharpCore.FREBitmapDataCLR, UInt32 ByRef) at TuaRua.FreSharp.Display.FreBitmapDataSharp..ctor(System.Drawing.Bitmap) at CefSharpLib.MainController.GetCapturedBitmapData(IntPtr, UInt32, IntPtr[]) at TuaRua.FreSharp.FreSharpMainController.CallSharpFunction(System.String, IntPtr ByRef, UInt32, IntPtr[]) at <Module>.callSharpFunction(Void*, Void*, UInt32, Void**)

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
no

**Comment by tuarua** [comment]
Please provide code which you can use to reproduce the problem.
It's not clear whether you are "calling many times per second" ?
Or a user it is random and initiated by user click etc.

**Comment by tuarua** [comment]
Please provide further details or I will have to close this ticket
