### ISSUE TITLE
Packaged version of app is showing a Cefsharp.WinForms v69 dependancy

### ISSUE THREAD

**Issue by wak932** [tuarua/WebViewANE#204]
- **What version of the product are you using?**
    - What version are you using?
2.2.1

- **On what operating system?**
win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
32bit (have also tried 64bit)

- **Which IDE are you using?**
IntelliJ

- **Which version of AIR are you using?**
32

- **What steps will reproduce the problem?**
works fine when run in the adl but...
package the app - run it and get the following error when the webview's init function is called:
CefSharp.WinForms, Version=69.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
Yes. Works out of the ide - package it with the adt and it dies.

**Comment by tuarua** [comment]
Sounds like you are using an older version of WebViewANELib.dll from c_sharp_libs_x86 when you package.
Make sure the c_sharp_libs_x86 files are the same in both the AIR bin and when you package your release.

**Comment by wak932** [comment]
I copied across all the dlls again from the latest release and it did seem to sort the version problem, but it still bombs out after packaging.
Is there an update to the FreSwift.ane that should accompany v.2.2.0 of the webview?

p.s. I believe my work has got in touch to comission you for some support :)

**Comment by tuarua** [comment]
I got the email earlier, thanks.

Please provide some further details:
You say it is erroring after packaging with adt.
Please use Event Viewer to find the error. 
Here is an example.

![image](https://user-images.githubusercontent.com/12083217/55825428-dfd4c600-5afd-11e9-93fd-043855a94c77.png)

Please also provide a screengrab of the build folder after you have packaged with adt. I want to see all the required files also reside in the same folder.

For example here is my folder when I package the AIR app from IntelliJ.
![image](https://user-images.githubusercontent.com/12083217/55826627-5a064a00-5b00-11e9-9dd6-4d301df539a6.png)

**Comment by tuarua** [comment]
Re: FreSwift.ane - this contains libraries for OSX so on Windows it's just a stub. It won't cause any errors and can be excluded if you are building only for Windows.
