### ISSUE TITLE
capture error in 2.1.1 use android7 

### ISSUE THREAD

**Issue by kofciva** [tuarua/WebViewANE#207]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
e.g. 1.8.0

- **On what operating system?**
    -  Win7 ?
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit

- **Which IDE are you using?**
    - Flash Builder 4.7?

- **Which version of AIR are you using?**
    - 32 etc?

- **What steps will reproduce the problem?**
    - use android After moving the page, you can't complete the screenshot by using the screenshot method. The function of the screenshot is normal only when the page is initialized.
 Webview used in the Apple system without problems

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**

**Comment by tuarua** [comment]
Fixed in 2.3.1
