### ISSUE TITLE
Execute Javascript outside the current tab

### ISSUE THREAD

**Issue by lgignoud** [tuarua/WebViewANE#209]
- **What version of the product are you using?**
    1.9.0

- **On what operating system?**
    WIN10
    
- **32bit** or **64bit**?
   32bit

- **Which IDE are you using?**
    IntelliJ

- **Which version of AIR are you using?**
    29

- **What steps will reproduce the problem?**

    I have 2 tabs in the WebView. Tab 1 is the current tab. I can't execute a javascript function on Tab 2 with `WebViewAne.callJavascriptFunction() `. Looking in CefView.cs:
```
public async void EvaluateJavaScript(string javascript, string callback) {
            try {
                var mf = CurrentBrowser.GetMainFrame();
                var response =
                    await mf.EvaluateScriptAsync(javascript, TimeSpan.FromMilliseconds(500).ToString());
                if (response.Success && response.Result is IJavascriptCallback) {
                    response = await ((IJavascriptCallback) response.Result).ExecuteAsync("");
                }

                Context.DispatchEvent(WebViewEvent.AsCallbackEvent, response.ToJsonString(callback));
            }
            catch (Exception e) {
                Context.DispatchEvent(WebViewEvent.AsCallbackEvent, e.ToJsonString(callback));
            }
}
```
I can see that the javascript function is executed only in the current tab (CurrentBrowser).

Is there a possibility to execute a javascript function in any tab, not only the current one ?

**Comment by tuarua** [comment]
I'm afraid it's not possible to execute JS in a tab other than the current one.

**Comment by lgignoud** [comment]
Ok, I end up queuing the JS functions for the tabs other than the current one, and execute them as soon as the tab becomes visible. Thanks for this great ANE anyway.
