### ISSUE TITLE
Problem with displaying WebGL in Android 8.0.0

### ISSUE THREAD

**Issue by bartekrs** [tuarua/WebViewANE#210]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - yes
    
- **What version of the product are you using?**
    - current (2.3.1)

- **On what operating system?**
    - Win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit

- **Which IDE are you using?**
    - Adobe Animate 19.2

- **Which version of AIR are you using?**
    - 32.0.0.116

- **What steps will reproduce the problem?**
visit https://get.webgl.org/ or any other page that contains WebGL.

- **What is the expected output? What do you see instead?**
Expected output: displaying WebGL 3D animation, instead site says:
,,Hmm, While your browser seems to support WebGL, it is disabled, or unavailable. If possible, please ensure that you are running the latest drivers for your video card. (...)''

- **Please provide any additional information below.**
There is a problem with displaying WebGL inside of WebViewANE in Android 8.0.0 (Chromium WebView 74), but tested on other Android devices and problem also occured.
In the Chrome browser, or WebView apps, (on the same device) WebGL seems to be working. 
My as3 code:

```
package {
import com.tuarua.FreSwift;
import com.tuarua.WebViewANE;
import com.tuarua.webview.Settings;

import flash.display.Sprite;
import flash.events.Event;
import flash.geom.Rectangle;
import flash.net.URLRequest;

public class WebViewExampleAS3 extends Sprite {
    private var freSwiftANE:FreSwift = new FreSwift();//must create before all others
    private var webview:WebViewANE = new WebViewANE();
    private var hasActivated:Boolean;

    public function WebViewExampleAS3() {
        this.addEventListener(Event.ACTIVATE, onActivated);
    }

    protected function onActivated(event:Event):void {
        if (hasActivated) return;
        hasActivated = true;
        var viewport:Rectangle = new Rectangle(0, 0, 1920, 1080);
        var settings:Settings = new Settings();
        webview.init(stage, viewport, new URLRequest("https://get.webgl.org/"), settings, 1, 0xFFF1F1F1);
        webview.visible = true;
    }
}
}
```

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**

**Comment by tuarua** [comment]
make sure hardware acceleration is enabled in <manifestAdditions> just like in the **sample application**. WebGL works for me on  multiple devices

See
https://github.com/tuarua/WebViewANE/blob/0ffc10a17d02f7782d78bba270d9ce6d02161517/example-mobile/src/WebViewANESample-app.xml#L95

**Comment by bartekrs** [comment]
It worked, thank you!
