### ISSUE TITLE
JavaScript Confirm - Is it OK to leave/reload this page?

### ISSUE THREAD

**Issue by davidenco** [tuarua/WebViewANE#213]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Yes
    
- **What version of the product are you using?**
    - 2.5.0

- **On what operating system?**
    - Win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - 64bit

- **Which IDE are you using?**
    - Flash Builder

- **Which version of AIR are you using?**
    - 32

- **What steps will reproduce the problem?**

1. Load a website that utilises a close confirmation (prompts before one can close the window).
2. Attempt to load() another URLRequest.

- **What is the expected output? What do you see instead?**
I understand why this is happening but there is no option to disable it. When attempting to load() another URLRequest, as popup appears:

![image](https://user-images.githubusercontent.com/11735630/59119022-99f37d00-8949-11e9-964e-ce1abbc8efbf.png)

Clicking OK allows the new URLRequest to take effect, otherwise the existing URLRequest remains. Hiding the WebView does not hide this popup. It's created by the OS so one has no choice but to click OK or Cancel before being allowed to use the AIR application.

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**

**Comment by tuarua** [comment]
You need to use Javascript to do this.
You can clear the onbeforeunload event they are using to do this

`webView.evaluateJavascript("window.onbeforeunload = null;");`

**Comment by davidenco** [comment]
That's an idea, but I couldn't just execute that after using load() as onbeforeunload could be set again by navigating to a page within the existing loaded session without calling load().

Therefore is there an event I can use to monitor content changes or page loads? I have tried the DOWNLOAD_* events when set before the load() call, but they never fire.

**Comment by tuarua** [comment]
Already answered here.
https://github.com/tuarua/WebViewANE/issues/140

Please study the extensive example provided with the project. A lot of time was spent building it. 
The tracker is for issues and not a general support forum.
