### ISSUE TITLE
OSX: BaseUrl is nil

### ISSUE THREAD

**Issue by aW4KeNiNG** [tuarua/WebViewANE#214]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    Yes
    
- **What version of the product are you using?**
    - 2.5.0

- **On what operating system?**
    - OSX

- **Which IDE are you using?**
    - IntelliJ

- **Which version of AIR are you using?**
    - 32

- **What steps will reproduce the problem?**
    - If you use loadHTMLString method, the baseURL isn't sent to OSX. 

    For example: `webView.loadHTMLString(htmlString, new URLRequest("http://localhost"));`

    It is important if you use services like Google API, where you need to use HTTP referrers. If the referrer doesn't match with the baseURL then the api call is rejected.

- **What is the expected output? What do you see instead?**
    Currently baseURL is `about:blank` (got from Google error). In the code baseURL seems to be `nil`: https://github.com/tuarua/WebViewANE/blob/a704108ae72267bcc269294e767ecd510a1e679e/native_library/apple/WebViewANE/WebViewANE/WebViewVC.swift#L123

**Comment by tuarua** [comment]
There was a reason I ignored baseUrl on OSX/iOS but I will look into again and add it.
Thanks for digging into the source.

**Comment by tuarua** [comment]
2.5.1 has now been released

**Comment by aW4KeNiNG** [comment]
Thanks!
