### ISSUE TITLE
Cef with h.264 Windows

### ISSUE THREAD

**Issue by jasonJamEther** [tuarua/WebViewANE#217]
In the past I have rebuilt chromium with H.264 support. I just recently upgraded to the latest version of the ane which includes all these libraries inside the ane (which is really convenient). But now is there any way for me to include the h.264 in Chromium? could the library maybe contain a flag to enable h.264 for those that havea license? I have tried the edge browser, but a lot of my local html files are not working that do work with chromium, sounds like edge has some extended cors restrictions of sorts.

**Comment by tuarua** [comment]
Can you please clarify if you have built **CefSharp** with H.264. It is not clear what you are expecting.
If you have re-built CefSharp with H.264 you can simply replace the relevant files inside the ane using 7-Zip (ANEs are really just a zip file)

> could the library maybe contain a flag to enable h.264 for those that havea license?
No. It's not that simple. Please see https://github.com/cefsharp/CefSharp/issues/873

**Comment by jasonJamEther** [comment]
I have rebuilt CefSharp, I didn't know I could just replace the files in the ANE. That is what I needed to know, thank you.

**Comment by tuarua** [comment]
Yes. You can Open the archive in 7-Zip and then drag-and-drop the files to replace

![image](https://user-images.githubusercontent.com/12083217/61335967-4d903c80-a827-11e9-9f21-4a7de67f9076.png)

**Comment by tuarua** [comment]
@jasonJamEther Do you have a crib sheet on how you compiled CefSharp? It could onto the wiki to help others.
It would be good for people to contribute back to the project.

**Comment by jasonJamEther** [comment]
Although I would love to help, I am afraid I am not a good resource on this. I did this over a year ago and it took me an embarrassing amount of time to figure out how to compile all the libraries together, just to enable mp4 capabilities. At this point I too would be starting from square one trying to figure out how to do this. If I do find myself needing to do it again I will make sure to write down all the workflow to post here. For now, I will just use Edge.
