### ISSUE TITLE
Error: The extension context does not have a method with the name init.

### ISSUE THREAD

**Issue by fftidus** [tuarua/WebViewANE#218]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    yes
- **What version of the product are you using?**
    - What version are you using?
2.6.0-beta

- **On what operating system?**
    Win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit

- **Which IDE are you using?**
    -Flash Builder

- **Which version of AIR are you using?**
    - 32

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.

webView.init(...)

- **What is the expected output? What do you see instead?**
ArgumentError: Error #3500: The extension context does not have a method with the name init.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.tuarua::WebViewANE/init()

**Comment by tuarua** [comment]
see
https://github.com/tuarua/WebViewANE/issues/196#issuecomment-451736964

**Comment by tuarua** [comment]
Closing, assumed answered
