### ISSUE TITLE
Can't open the third party app like Alipay.

### ISSUE THREAD

**Issue by fftidus** [tuarua/WebViewANE#222]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
2.6.0

- **On what operating system?**
Win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
64bit

- **Which IDE are you using?**
 Flash Builder

- **Which version of AIR are you using?**
33

- **What steps will reproduce the problem?**

window.document.write(formurl);

the formurl is:
"<... name="punchout_form" method="post" action="https://openapi.alipay.com/gateway.do?charset=UTF-8&method=alipay.trade.wap.pay&sign=LJlapjjCeO1s2q6k%2BLcAP74ySbQLrSOFrC%2BkMGvDltkzk943jaN35JhaMNTR%2B3%2FE9CexrgXwkj6p9fTKscUKCMp2ellVZQy7f8ywuUca4UezstxsYwEepywstxWmzZxKCHQaL25R2taiIUIAE%2F0gt3g7GzNtxFqAfPBBaRByDVKV7Mjuvw3S1r7jXvlKJkYdd1p2%2BRmGRxnPoYDx0Jpx%2BI8Hv0KoUDH6v8GYpBxKgoSaDRSxDRBjmF6Whjjb7ovZCOAoMGCfafMSwV39KZUxLdZts6K%2FLAfcNmBF72LM9WhNsJKQqqTvna1FvJEeol0%2B2taBnnkcB9jrRss6ELRQpg%3D%3D&version=1.0&app_id=2018070360533246&sign_type=RSA2&timestamp=2019-08-21+09%3A51%3A32&alipay_sdk=alipay-sdk-java-3.7.26.ALL&format=json">
<input type="hidden" name="biz_content" value="{&quot;out_trade_no&quot;:&quot;zzl20190821095132010&quot;,&quot;passback_params&quot;:&quot;%E5%B0%91%E5%84%BF%E4%B8%93%E6%B3%A8%E5%8A%9B_1db88173%3A7617595647247_%5B7%2C8%5D_%E5%A4%9A%E8%AF%BE&quot;,&quot;product_code&quot;:&quot;QUICK_MSECURITY_PAY&quot;,&quot;subject&quot;:&quot;&quot;,&quot;total_amount&quot;:&quot;0.01&quot;}">
<input type="submit" value="立即支付" style="display:none" >
</form>
<script>document.forms[0].submit();</script>"

And it will goto "https://mclient.alipay.com/cashier/mobilepay.htm?alipay_exterface_invoke_assign_target=invoke_77625569aa6cd0399c0ed05d31fa2d2a&alipay_exterface_invoke_assign_sign=_y_epd_e_ntm_l8_x_sjal_b_pyy_p_bj%2Fi_v8_buq_w6cn_fh_v_lbh_r_v0_hzc_e4a_qk_t_zx_a%3D%3D" and open the Alipay app.

but now is not worked.

If i add the "https://mclient...." to the urlBlackList,and use "navigateToURL()" instead, it works!

**Comment by tuarua** [comment]
This is likely a problem with your code.
You will need to debug yourself.
I can only investigate issues with the ANE.

**Comment by fftidus** [comment]
> This is likely a problem with your code.
> You will need to debug yourself.
> I can only investigate issues with the ANE.

but if I use the Air's stageWebView, this code will run and call "alipay://....", but in this ANE the url won't be found in "ON_PROPERTY_CHANGE" handler.
