### ISSUE TITLE
ParseException: bad class file magic (cafebabe) or version (0034.0000)”

### ISSUE THREAD

**Issue by tuarua** [tuarua/WebViewANE#224]
I noticed that you are using Adobe AIR 33 released by Harman
When I am using Adobe AIR 32 originally from Animate 2019,
publishing in android apk(ARM) with blank project (only WebViewANE.ane included),
ParseException: bad class file magic (cafebabe) or version (0034.0000)” still occurred
any solution?

_Originally posted by @suwenyung in https://github.com/tuarua/WebViewANE/issues/216#issuecomment-527890964_

**Comment by tuarua** [comment]
Dupplicate of #221

**Comment by suwenyung** [comment]
Thanks for your reply

>
