### ISSUE TITLE
can't build on osx for ios (unknown ABI version 0x07)

### ISSUE THREAD

**Issue by jaco-pixeldump** [tuarua/WebViewANE#227]
hi,

- osx: 10.14.6
- xcode: 11.0 (11A420a), build for swift 4.2
- carthage update for swift-ios-ane  freswift to 4.0.0, since 3.1.0 is not compatible with actual toolchain
- regular licensed intellij 2019.2
- both air sdk 32 (latest from adobe labs) and 33 from harman
- ios_dependencies 2.8.0

ane builds correctly after some refinements (paths, carthage, build settings), it results in circa 2.5 MB

I'm trying to update an app which worked till a couple of weeks ago. Now I receive this error, no matter if I try against sdk 32 or 33, always end with this message:

ld: /var/folders/2r/37p4c3z117l406j5r6sg37z00000gn/T/ca4f0914-2a5f-4d8f-bff0-8732ba11572a/Frameworks/WebViewANE_FW.framework/WebViewANE_FW compiled with newer version of Swift language (unknown ABI version 0x07) than previous files (unknown ABI version 0x06) file '/var/folders/2r/37p4c3z117l406j5r6sg37z00000gn/T/ca4f0914-2a5f-4d8f-bff0-8732ba11572a/Frameworks/WebViewANE_FW.framework/WebViewANE_FW' for architecture armv7

Compilation failed while executing : ld64Also tried to change toolchain with previous swfit by open source, they don't build in xcode.

* I'll try with example app asap.

Thanx in advance

Jaco

**Comment by tuarua** [comment]
The error explains the problem. It is saying the previous version cached is using a different ABI Swift version. 
Try clearing that folder out.
/var/folders/2r/37p4c3z117l406j5r6sg37z00000gn/T/ca4f0914-2a5f-4d8f-bff0-8732ba11572a

You are not allowed upgrade the base SDK / Swift and not increase the app/framework version
Make sure you bump the FW version in info.plist.
Also the version of you AIR app.

**Comment by jaco-pixeldump** [comment]
hello, thanks for your reply

Of course I've already cleaned up /var/folders before opening issue, error still persist after different attempts.
my plist is untouched from repo (2.8.0)
I'll report if sample app works

**Comment by tuarua** [comment]
> xcode set to build against swift 4.2

FreSwift 4.0 is built against swift **5**

**Comment by jaco-pixeldump** [comment]
Yes, of course I know about abi topic.

got finally direction, also get_ios_dependencies.sh need to be adjusted to point to 4.0.0 instead of 3.1.0
To let compile it should be updated Cartfile and that bash file.

* now there are other severe issues, but they come from ios 13, another story ...

thank you.
