### ISSUE TITLE
Variable com.tuarua.fre :: ANEError is not defined - on new FB project

### ISSUE THREAD

**Issue by gdeverlant** [tuarua/WebViewANE#229]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
   Yes
    
- **What version of the product are you using?**
    - What version are you using?
2.8.0

- **On what operating system?**
    Win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
    32bit

- **Which IDE are you using?**
    Flash Builder

- **Which version of AIR are you using?**
    31

- **What steps will reproduce the problem?**
    basic setup
- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

![image](https://user-images.githubusercontent.com/26530975/66254102-13716f80-e772-11e9-9383-47f6c957fbe0.png)

![image](https://user-images.githubusercontent.com/26530975/66254114-41ef4a80-e772-11e9-875f-64c7c8c99eaf.png)

Didn't used that sample, but just copied the code.

**Comment by gdeverlant** [comment]
This line :  
````
private var freSwiftANE:FreSwift = new FreSwift(); // must create before all others
````

I could not find that ANE file that's why i removed it.

**Comment by tuarua** [comment]
https://github.com/tuarua/WebViewANE/wiki/Troubleshooting---FAQs#when-i-use-flex-i-received-error-variable-comtuaruafre--aneerror-is-not-defined

https://github.com/tuarua/WebViewANE/wiki/Troubleshooting---FAQs#i-am-not-able--to-add-the-anes-to-my-flash-builder-project

> Didn't used that sample, but just copied the code.
Then the problem is on your side.

**Comment by gdeverlant** [comment]
Ok it works well but unfortunately the resizing seems to be problematic.

![image](https://user-images.githubusercontent.com/26530975/66592710-e4099b00-eb95-11e9-8200-da9a48ae68a7.png)

In normal browser it is centered all

![Uploading image.png…]()
