### ISSUE TITLE
Shared runtime

### ISSUE THREAD

**Issue by hferreira** [tuarua/WebViewANE#23]
Great job with your ANE !
Tested on OSX.

I saw a lot of dependencies on Windows side (.NET 4.5.2 + C++ 2013 + C++ 2015) and a tutorial to make this work with AIR (so for captive runtime).
Does this means that your ANE does not work on Windows side with shared runtime ?

Thank you,
Hugo.

**Comment by tuarua** [comment]
It should work with the shared runtime, provided all the same required dependencies are included inside the package. Please do test to confirm.

**Comment by hferreira** [comment]
Thank you.
