### ISSUE TITLE
ADL just crashes when instantiating WebViewANE [FlashDevelop]

### ISSUE THREAD

**Issue by datee** [tuarua/WebViewANE#232]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
**Yes, it does not solve my issue.**
    

- **What version of the product are you using?**
    - What version are you using?
**2.8.0, but have tried with several eariler versions also, same issue**

- **On what operating system?**
    - OSX, Win7, Win 8, Win10, etc?
**Win10**
    

- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit or 64bit
**32bit**

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?
**FlashDevelop**

- **Which version of AIR are you using?**
    - 29,30.. etc?
**have tried with 27/31/32**

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
**Just a normal project setup and run in debug/release**

- **What is the expected output? What do you see instead?**
**ADL just crashes when new WebViewANE() is run. Just closes, no visible error message**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.
**There is no error message, ADL just closes**

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
**Yes, same issue**

-I did a project 2 years ago using an old version of this ANE, and that version of the ANE still works fine, but newer versions just crash, unable to find an error message..

-Have tested setup on several computers, the issue is the same on all of them.

**Comment by tuarua** [comment]
- It sounds like you didn't delete the binary files (dlls, bins etc) from your AIRSDK/bin folder.
You used to add them into this folder but now they are packaged inside the ANE.
- Or you didn't add the now required FreSharp.ane

This is prominently explained in the readme and the wiki.

> ## Important notice for Windows version of 2.5.0+
> C# and CefSharp binaries are now packaged inside the ANE. All of these **need to be deleted** from your AIRSDK.     
> [FreSharp.ane](https://github.com/tuarua/FreSharp/releases) is now a required dependency for Windows.

**Comment by datee** [comment]
Yes, i have read the Wiki and ofcourse checked this. I have added the FreSharp.ane and it instantiates without a crash no problem, its the new WebViewANE() that crashes ADL. I am running from a newly downloaded AIR SDK with no CEF binaries, and the error is the same.  I even tried on 2 different computers and the result is exactly the same.

Are there any other reasons for this to happen? Any way i can get a log or error so i can find the cause?

**Comment by tuarua** [comment]
> Are there any other reasons for this to happen?
Download the ANE again to ensure it was not corrupted. No-one else has reported adl crashing like you have.

> Any way i can get a log or error so i can find the cause?

To retrieve the error open Event Viewer > Windows Logs > Application and look for the error

**Comment by datee** [comment]
Yes, i'm aware that there is no previous issue on this, but thats why im posting this. Looking at the event logs i can extract the following info:

```
Application: adl.exe Framework Version: v4.0.30319 Description: The process was  terminated due to an unhandled exception. Exception Info:  System.ArgumentException at <Module>.FreSharpBridge.InitController() at  <Module>.TRWV_contextInitializer(Void*, Byte*, Void*, UInt32*,  FRENamedFunction_**)
--
```
Hope its gives an indication into where the problem might be!

**Comment by tuarua** [comment]
I don't use FlashDevelop but I have been able to reproduce the error with that. Looks to be something specific to how it loads ANEs - different to other IDEs. It will take a week or 2 for me to investigate and fix.

**Comment by tuarua** [comment]
With Flashdevelop you would have modified run.bat and added -extdir {folderName} to one of the lines.
If you entered a relative path try changing it to an absolute path eg -extdir C:\Myproject\anes_unzipped
The assemblies need to know what the search base folder is and have no way of knowing what a relative path is relative to.

**Comment by datee** [comment]
Great! This solves the crash issue and now it works like expected! A note on this for FD users would be helpful then i guess! Thank you! :)
