### ISSUE TITLE
Incorporate Ultralight instead of CEF

### ISSUE THREAD

**Issue by gdeverlant** [tuarua/WebViewANE#233]
I found out this project which might reduce the size of the whole thing down to few MBs.

https://github.com/ultralight-ux/Ultralight

Do you think this could become a good alternative?

**Comment by tuarua** [comment]
I don't think this is a viable alternative. 
- It is proprietary and businesses need to pay for a commercial license.- It is missing key features like video/audio/webgl support. - It looks very immature with many open bugs, even for basics like form rendering and css bugs. (last release was > 6 months ago)
So no, I won't be replacing the gold standard CEF with this.You can use Edge version of the ANE if the size of Chromium is a problem. 

Sent from Yahoo Mail on Android 
 
  On Fri, 13 Dec 2019 at 0:53, gdeverlant<notifications@github.com> wrote:   
I found out this project which might reduce the size of the whole thing down to few MBs.

https://github.com/ultralight-ux/Ultralight

Do you think this could become a good alternative?
