### ISSUE TITLE
White screen of death triggered by change in opacity (CSS)

### ISSUE THREAD

**Issue by codeandvisual** [tuarua/WebViewANE#234]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    Yes
    
- **What version of the product are you using?**
  2.8.0

- **On what operating system?**
   Win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
     32bit 

- **Which IDE are you using?**
     Flash Develop

- **Which version of AIR are you using?**
   32

- **What steps will reproduce the problem?**
Hi, we're using your ANE to create a kiosk app that displays local files. All is working well except for some very specific combination of events when we get a "white screen of death" in which the app hangs.  When all of these factors are in play, the issue will occur:

1. Air is set to fullscreen interactive
2. It's the first time the HTML file is displayed (Will work fine on following attempts)
3. HiDPI is set to true

With all of the above in play, the crash occurs when an opacity fade on the body content is triggered via JavaScript (or by using the devtools styles editor).

- **What is the expected output? What do you see instead?**

The HTML page should render correctly. Instead the screen goes white. I can load the same page with the CSS and JS stripped out and there are no issues. A successive return to the page (i.e. reloading the app and viewing again) will allow the page to render fine with no problems (this time with JS and CSS in tact).

- **Please provide any additional information below.**
The chromium dev tools display an error message that says:

> Debugging conection was closed. Reason: Render process gone.

It seems to be a crash in CEF and I've caught an error dump which lists the stack as:

> Function     Arg 1     Arg 2     Arg 3     Arg 4   Source 
> KERNELBASE!RaiseException+62     e0000008     00000001     00000001     0e3ff61c    
> libcef!cef_string_utf16_to_upper+421b1     03380000     0e3ff6b4     06e5d509     03380000    
> libcef!cef_string_utf16_to_upper+4218f     03380000     00000000     0e3ff638     00000000    
> libcef!cef_string_utf16_to_upper+4234ad     0e3ff6ec     03380000     00000007     0b959b78    
> libcef!cef_string_utf16_to_upper+4231e3     0e3ff7a8     0337f980     0e3ff6f8     00000002    
> libcef!GetHandleVerifier+166bff9     12d41804     12d41b10     00000000     0e802064    
> libcef!GetHandleVerifier+166e0d8     12d41804     00000000     077f03f2     12d417d0    
> libcef!GetHandleVerifier+1671633     00000000     7744b499     0b8c0c50     00000005    
> libcef!GetHandleVerifier+14013f3     00000001     0b8c0c50     0b9563f8     0b8c0cc0    
> libcef!GetHandleVerifier+1400e85     0b9563f8     0b8c0c68     0b9563b8     0e3ff970    
> libcef!GetHandleVerifier+1400e25     0b9563f8     0b8c0cc0     0e3ff98c     06a9b93a    
> libcef!GetHandleVerifier+14016a4     34303632     00000000     04000000     0e68cba0    
> libcef!cef_string_utf16_to_upper+618de     0b9563b8     000006bc     000006bc     12ccb133    
> libcef!cef_string_utf16_to_upper+60de9     0b899918     76d80400     0e3ffa1c     7745662d    
> kernel32!BaseThreadInitThunk+19     0b899918     afb4f42c     00000000     00000000    
> ntdll!__RtlUserThreadStart+2f     ffffffff     774751d7     00000000     00000000    
> ntdll!_RtlUserThreadStart+1b     06a9adb0     0b899918     00000000     00000000    
> 

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
I haven't tried this but I think it's a particular combination of our HTML files and am guessing there's some javascript or CSS that is triggering a crash so this probably wouldn't happen with your files.

**Comment by codeandvisual** [comment]
Ps - the Windows Event Viewer lists the following info:

> Fault bucket 2179634576725957247, type 1
> Event Name: APPCRASH
> Response: Not available
> Cab Id: 0
> 
> Problem signature:
> P1: CefSharp.BrowserSubprocess.exe
> P2: 75.1.142.0
> P3: 5d7609b3
> P4: KERNELBASE.dll
> P5: 10.0.17763.914
> P6: 6cc9b5fd
> P7: e0000008
> P8: 001219b2
> P9: 
> P10: 


and

> Application: CefSharp.BrowserSubprocess.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: exception code e0000008, exception address 752C19B2

**Comment by tuarua** [comment]
As this is a CEF crash you would be better served by opening an issue on the CEF forum. There's not alot I can do if the problem is coming from the underlying engine. You will likely be required to provide exact JS+CSS code which reproduces the problem.

https://magpcss.org/ceforum/viewforum.php?f=6

You may consider the following:

- Does it only occur on the kiosk Windows device or on your dev machine(s) also. It could be a graphics card quirk.
- I am unable to reproduce the problem myself. I set opacity on the body using devtools with no crash (in FS and using hiDPI).
- try setting `settings.useTransparentBackground = true/false;` to see if it makes a difference
- try setting opacity on a wrapping `div` container instead of the `body` tag.

**Comment by codeandvisual** [comment]
Thanks, I think you're right - I was able to resolve the issue 

The "first time the HTML is displayed" aspect of my description ended up being more of a "first time the app was run" issue. This was because of the use of the fzip class to unpack some files. 

Objects created in the process look like the weren't being cleared properly. By using the content.clear() function on these this has now resolved the issue with WebViewANE.


Thank you for looking in to it, and thanks for your great Native Extension.
