### ISSUE TITLE
Why doesn't the .isSupported option exist?

### ISSUE THREAD

**Issue by lwmirkk** [tuarua/WebViewANE#235]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
Yes    

- **What version of the product are you using?**
    - What version are you using?
2.8.0

- **On what operating system?**
    - Win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit, 64bit

- **Which IDE are you using?**
    - FlashCC

- **Which version of AIR are you using?**
    - 32.0.0.89

- **What steps will reproduce the problem?**
    - webview.isSupported

- **What is the expected output? What do you see instead?**
    - Check if the ANE .isSupported in the curent system / os.

- **Please provide any additional information below.**
    - How to check if the ANE is supported in the current system? I will provide my app only in Android 19+ and Windows 7+... In Android will be no problem, in Windows I will install the dependencies (.NET and VC) with Inno, but if the user uninstall one of these dependencies or if the install of them fail, how can I check if the ANE will work in the user side? Most of ANE have this option: .isSupported.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
    - WebViewANE

Thanks a lot. =)

**Comment by tuarua** [comment]
an ANE written in C++ can't give a method to check if C++ is installed. Think about it.

~99% of PCs already have .NET and VC already installed. The installer covers the 1% of cases.

> if the user uninstall one of these dependencies 

If the user starts messing about uninstalling MS libraries they will brick most programmes on their PC. 

> Why doesn't the .isSupported option exist?

Because it is implicitly `true` - the ANE is supported on every os of past 5-10 years.
