### ISSUE TITLE
How change WebView viewport (width / height) after init()?

### ISSUE THREAD

**Issue by lwmirkk** [tuarua/WebViewANE#236]
- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Yes
    
- **What version of the product are you using?**
    - 2.8.0

- **On what operating system?**
    - Win10, Android
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit and 64bit

- **Which IDE are you using?**
    - Animate

- **Which version of AIR are you using?**
    - 32.0.0.89

- **What steps will reproduce the problem?**
    - Trying to change the width / height of webview viewport some time after already initiated.

- **What is the expected output? What do you see instead?**
    - Resize of webview / webview viewport.

- **Please provide any additional information below.**
    - If the user rotate the app with webview.visible = true; How adjust the viewport size?

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
    - WebViewANE

Thanks a lot. =)

**Comment by tuarua** [comment]
The project comes with a complete example.
Please study it. 
https://github.com/tuarua/WebViewANE/blob/fb80e726a79ac4f0ae098619c04ec99d6d9da795/example-desktop-complete/src/WebViewANESample.as#L474

Issue tracker is for bugs only
