### ISSUE TITLE
Context3D not available! Possible reasons

### ISSUE THREAD

**Issue by lucasreisprestes** [tuarua/WebViewANE#24]
I'm getting the following error when trying to run the sample.

`[Starling] Mask support requires 'depthAndStencil' to be enabled in the application descriptor.
[Starling] Context3D not available! Possible reasons: wrong renderMode or missing device support.`

I'm using AIR SDK 25 in Adobe Flash Professional with windows 7.

**Comment by tuarua** [comment]
You need to set up you app descriptor xml correctly like in the example.

https://github.com/tuarua/WebViewANE/blob/master/example/src/WebViewANESample-app.xml#L118

Please this for directions in how to setup on Windows for Animate
https://github.com/tuarua/WebViewANE/issues/14
