### ISSUE TITLE
Is the ANE available for download

### ISSUE THREAD

**Issue by ukmunnithan** [tuarua/WebViewANE#247]
Could you please share the ANE for testing purpose. I could not able to find the ANE from the path.

**Comment by esidegallery** [comment]
https://github.com/tuarua/WebViewANE/releases

**Comment by tuarua** [comment]
Make sure to read the wiki https://github.com/tuarua/WebViewANE/wiki

N.B. For future reference Issue tracker is for bug reports only.

**Comment by ukmunnithan** [comment]
I have added the Webview Ane in the app. The app is installing on my device. But I could not open the app. Could you please share any sample code?
