### ISSUE TITLE
Packages are not supported when using legacy build locations, but the current project has them enabled

### ISSUE THREAD

**Issue by 1395881288** [tuarua/WebViewANE#248]
**I'm sorry to bother you.**

Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
      yes
- **What version of the product are you using?**
    - What version are you using?
      2.10.0

- **On what operating system?**
    - OSX, Win7, Win 8, Win10, etc?
      OSX
- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit or 64bit

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?
     IntelliJ  ,  xcode 11.4 (11E146)  , macOS Catalina 10.15.4 (19E287)
- **Which version of AIR are you using?**
   33
- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
   when I open WebViewANE.xcodeproj, it show an error
   
<img width="949" alt="1" src="https://user-images.githubusercontent.com/24973451/83970649-5ee3ab00-a909-11ea-8506-60e3739b549c.png">

**Comment by tuarua** [comment]
As the error says you are using the Legacy Build System.

Use the **New Build System**

File > Project Settings

![image](https://user-images.githubusercontent.com/12083217/83971571-ef06fd80-a8d3-11ea-831f-74c35299c346.png)

**Comment by 1395881288** [comment]
I'm sorry to bother you.
I have set New Build System,but the mistake is still unresolved，So I did the following
<img width="471" alt="1" src="https://user-images.githubusercontent.com/24973451/84129170-33310400-aa74-11ea-8a0d-478a230b7d39.png">
<img width="892" alt="1" src="https://user-images.githubusercontent.com/24973451/84129217-4217b680-aa74-11ea-9977-68e5c485e016.png">

I successfully compiled ane，I run example-mobile，it Flashback，this is log
<img width="785" alt="1" src="https://user-images.githubusercontent.com/24973451/84129442-8a36d900-aa74-11ea-8ced-596e8b17375b.png">
