### ISSUE TITLE
Packages are not supported when using legacy build locations, but the current project has them enabled

### ISSUE THREAD

**Issue by 1395881288** [tuarua/WebViewANE#249]
**I'm sorry to bother you.**

Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
      yes
- **What version of the product are you using?**
    - What version are you using?
      2.10.0

- **On what operating system?**
    - OSX, Win7, Win 8, Win10, etc?
      OSX
- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit or 64bit

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?
     IntelliJ  ,  xcode 11.4 (11E146)  , macOS Catalina 10.15.4 (19E287)
- **Which version of AIR are you using?**
   33
- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
   when I open WebViewANE.xcodeproj, it show an error
   
<img width="949" alt="1" src="https://user-images.githubusercontent.com/24973451/83970649-5ee3ab00-a909-11ea-8506-60e3739b549c.png">

I have set New Build System,but the mistake is still unresolved，So I did the following
<img width="376" alt="1" src="https://user-images.githubusercontent.com/24973451/84129981-3d9fcd80-aa75-11ea-901e-a15f89ae4369.png">

<img width="471" alt="1" src="https://user-images.githubusercontent.com/24973451/84129170-33310400-aa74-11ea-8a0d-478a230b7d39.png">
<img width="892" alt="1" src="https://user-images.githubusercontent.com/24973451/84129217-4217b680-aa74-11ea-9977-68e5c485e016.png">

I successfully compiled ane，I run example-mobile，it Flashback，this is log
<img width="785" alt="1" src="https://user-images.githubusercontent.com/24973451/84129442-8a36d900-aa74-11ea-8ced-596e8b17375b.png">

**Comment by tuarua** [comment]
This the contents of the project Cartfile
https://github.com/tuarua/WebViewANE/blob/3cdb431e2ca0f76476211ae5213740e7731d6a6a/native_library/apple/WebViewANE/Cartfile#L1

If you have decided  add SwityJSON as a dynamic framework (why?) and then **forgotten** to include it with you AIR package then you are misrepresenting this as a problem with the project.
It's not.

Issue will be closed. Don't open any more.
