### ISSUE TITLE
tab switching causes taskbar button to flash orange on windows

### ISSUE THREAD

**Issue by Mwni** [tuarua/WebViewANE#251]
Version 2.10.0
Win7, Win 8, Win10
AIRSDK 32

When switching, creating or closing tabs programatically while in background, it causes the program's taskbar icon to flash/blink orange until focus is reassigned.

This is not occuring on OSX.

I'm guessing it's a "feature" of the Chromium engine, i've seen this weird behaviour on the spotify desktop app aswell, presumabily due to internal tab switches aswell.

More infos greatly appreciated.

**Comment by tuarua** [comment]
I don't have any more info on this.
If you are also seeing it on Spotify it sounds like built in Windows + Chromium interaction.
It's not something I have any control over.
