### ISSUE TITLE
window.opener is null for popup on OSX

### ISSUE THREAD

**Issue by wverhoeven** [tuarua/WebViewANE#253]
Answer the below. **DO NOT DELETE!!**
    
- **What version of the product are you using?**
    - What version are you using?
- 2.10.0

- **On what operating system?**
    - OSX

- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit or 64bit

- **Which IDE are you using?**
    - Flash Builder

- **Which version of AIR are you using?**
    - 32

- **What steps will reproduce the problem?**
    - Call window.opener from popup in OSX

- **What is the expected output? What do you see instead?**
  -window.opener is correctly referenced in the CefSharp version, but it is null in WKWebView

- **Please provide any additional information below.**
    - window.opener is necessary to post messages to the parent window via javascript. Is there another way to reference the opener?

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
window.opener is not referenced in sample app

**Comment by tuarua** [comment]
I can reproduce and needs further investigation
