### ISSUE TITLE
No focus on input with touch, requires mouse click

### ISSUE THREAD

**Issue by win3k** [tuarua/WebViewANE#255]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    - Yes
- **What version of the product are you using?**
    - What version are you using?
    - 2.10.0

- **On what operating system?**
    - OSX, Win7, Win 8, Win10, etc?
    - Win10
- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit

- **Which IDE are you using?**
    - Animate

- **Which version of AIR are you using?**
    - 32

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
    Launch webview with a site that needs text input, 
    launch windows onscreen keyboard, 
    touch input field and  try to type something, won't work until input field is clicked with mouse

- **What is the expected output? What do you see instead?**
- Expected is that touching the input will focus just as a mouse click

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
- Yes

**Comment by tuarua** [comment]
Run the **example-desktop-complete** example included and click on the **JS** button in the menu bar.

Windows touch requires a javascript workaround to focus on the webview.

https://github.com/tuarua/WebViewANE/blob/master/example-desktop-complete/src/jsTest.html#L62

https://github.com/tuarua/WebViewANE/blob/master/example-desktop-complete/src/WebViewANESample.as#L121

**Comment by win3k** [comment]
Hi, I have the fix in place and it works fine on start, but once the stage is touched and you then touch the input box the fix is called, but the osk input is not wotking. You then need to first click it again with the mouse.
[webviewdemo.zip](https://github.com/tuarua/WebViewANE/files/4850429/webviewdemo.zip)

**Comment by win3k** [comment]
Fixed it!
Thanks for the support!
