### ISSUE TITLE
EdgeView For Flex(Air)

### ISSUE THREAD

**Issue by Freyrair** [tuarua/WebViewANE#258]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
I've read the wikis and asdocs.
    
- **What version of the product are you using?**
WebViewANE.Edge.ane（2.11.0）

- **On what operating system?**
Win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
64bit

- **Which IDE are you using?**
Flash Builder 4.6

- **Which version of AIR are you using?**
AIR SDK 32.0

- **What is the expected output? What do you see instead?**
Based on the examples provided by you, my local flex (air) project has been able to run (Windows chromium) browser。
now I still want to try the related functions of (windows edgeview), so local project is associated with WebViewANE.Edge.ane .the EdgeView can not run successfully, and I can not found the relevant instructions, so I want to ask you for help, have you used (windows Edgeview) related documentation or example?

**Comment by tuarua** [comment]
You need to set the engine if you are using Edge.

https://github.com/tuarua/WebViewANE/blob/master/example-desktop-complete/src/WebViewANESample.as#L149

Please study example-desktop-complete and the asdocs

**Comment by Freyrair** [comment]
First of all, thank you for your answer
Question 1:
Before asking the questions, my local project has set up engine, and I confirmed during debugging that it is set to WebEngine.EDGE, only a gray background was displayed on the screen,  the web page can not successfully display and the exception information is not output.

※the Local codding source:
var freSharpANE:FreSharp = new FreSharp(); // must create before all others
var freSwiftANE:FreSwift = new FreSwift(); // must create before all others
var webView:WebView;

var viewPort:Rectangle = new Rectangle(0, 0, 300, 300);
var settings:Settings = new Settings();
settings.engine = (os.isWindows && os.majorVersion >= 10 && os.buildVersion >= 17134)
		? WebEngine.EDGE
		: WebEngine.DEFAULT;
		
webView = WebView.shared();
webView.init(e.currentTarget.stage, viewPort, new URLRequest("https://html5test.com"), settings, 1.0, 0xFFF1F1F1);
webView.visible = true;

Question 2:
I have the following problems when I use chromium view. I hope you can help me answer them.
There are the following functions in my flex project , click different buttons to call up different pop-up pages (load HTML content). 
Now I use chromium view to load the pop-up page content. First, clicking the first button, the first pop-up page can be displayed normally, and then the First pop-up window is closed. When I click the second button open the second popup window, WebView failed to load;

I tried the following, but failed：
At the end of the first screen, WebView is unload; when the second screen pops up, WebView reloads (shared(); init());
1).First popup-closeEvent:
 WebView.dispose ();
 FreSwift.dispose ();
 FreSharp.dispose ();

2).the second popup-openEvent:
var freSharpANE:FreSharp = new FreSharp(); 
var freSwiftANE:FreSwift = new FreSwift();

webView = WebView.shared();
webView.init(e.currentTarget.stage, viewPort, new URLRequest("https://secondHtml.com"), settings, 1.0, 0xFFF1F1F1);
webView.visible = true;

**Comment by esidegallery** [comment]
Not sure about question 1. I assume you’re running in Windows 10?

To answer question 2, you shouldn’t dispose the web view. It should be initialised once, then shown/hidden as needed.

**Comment by Freyrair** [comment]
Question 1:
As you can guess, the running environment is windows 10. The system version is 2019.
The Edgeview runs on window10. Does it need other system requirements?

Question 2:
Now I open the pop up page using the Class (spark.components.Window). After the screen is completed, the webView is loaded to the popup window;
I try to use the method [webView.load (newUrl)] can load other web page content again, but the content is loaded on the first popup Window.
I guess the reason is that when the WebView is initially initialized, the stage is set for it. The next time load URL is used, the new content will be bound to the original Window's stage. Therefore, can we add another parameter stage to the load method to solve the above problem?
Or can you suggest a better solution: after a new window pops up, use the WebView to load HTML content?

**Comment by tuarua** [comment]
As per the[ FAQS](https://github.com/tuarua/WebViewANE/wiki/Troubleshooting---FAQs)

#### Can I run multiple WebViews?
No. Only one instance of WebViewANE can be created and used.

However, the view can be shown and hidden when not in use via the visible setter/getter
eg.

`webView.visible = false;`

***

#### Are multiple AIR windows supported?
No. There is no reliable way to attach the webview processes to AIR child windows.

Essentially you are assuming the WebView is like a Flash component. 
It's not. The WebView is a native component which is rendered into the AIR window. It appears above the Flash display list. It is technically a separate window running it's own process.
It can only be used in your Main class and inited once per App.
