### ISSUE TITLE
Invalid URI Error when loading an unreachable URL without specifying URI scheme

### ISSUE THREAD

**Issue by esidegallery** [tuarua/WebViewANE#262]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Yes
    
- **What version of the product are you using?**
    - 2.12.0

- **On what operating system?**
    - Win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit

- **Which IDE are you using?**
    - VS Code

- **Which version of AIR are you using?**
    - 32.0

- **What steps will reproduce the problem?**
    - Using the example application, navigate to "suffolkarchives.co.uk" (omitting the URI scheme and subdomain)

- **What is the expected output? What do you see instead?**
    - I expect to see the cloudflare Error 523 page, as per other browsers. Instead, the application crashes

- **Please provide any additional information below.**
    - The following is displayed in the debug console:
> Error: Invalid URI: The format of the URI could not be determined.
>	at flash.external::ExtensionContext/_call()
>	at flash.external::ExtensionContext/call()
>	at com.tuarua::WebView/load()[/Users/eoinlandy/flash/WebViewANE/native_extension/src/com/tuarua/WebView.as:288]
>	at WebViewANESample/onUrlEnter()[C:\Users\timwj\Work\Resources\Actionscript Libraries\WebViewANE\example-desktop-complete\src\WebViewANESample.as:293]
>	at flash.events::EventDispatcher/dispatchEventFunction()
>	at flash.events::EventDispatcher/dispatchEvent()
>	at views::Input/onKeyUp()[C:\Users\timwj\Work\Resources\Actionscript Libraries\WebViewANE\example-desktop-complete\src\views\Input.as:60]

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
    - Yes

**Comment by tuarua** [comment]
Any url checking/cleaning should be done in your client.

I am unable to do this inside the ANE as I can't assume the prefix
eg localhost _might_ want to be http:// web urls _might_ want to be https://

Before passing a url to load you could do 
```
if !url.startsWith(https://) {
  url = https:// + url
}
```
