### ISSUE TITLE
WebView does not display correctly after changing the Windows 10 scaling value > 100%

### ISSUE THREAD

**Issue by lgignoud** [tuarua/WebViewANE#263]
- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    Yes
    
- **What version of the product are you using?**
   2.12

- **On what operating system?**
   Win 10
    
- If Windows is the AIR app **32bit** or **64bit**?
    64bit

- **Which IDE are you using?**
   IntelliJ

- **Which version of AIR are you using?**
   32

- **What steps will reproduce the problem?**
    On Windows 10, the option in Settings > System > Display > Scale and Layout causes some display issues when not set to 100%. You have to start the application after changing the value to see the problem. The WebView seems to translate to the right and bottom, and the text on a Flex application is blurry as soon as a WebView is opened. Is there a way to keep the WebView in its original position, regardless of the Windows scaling value  ?
 

With 100%:
![50%](https://user-images.githubusercontent.com/36662547/94450891-1ac53080-01ae-11eb-9947-8a6245c928c6.png)

With 125%:
![125%](https://user-images.githubusercontent.com/36662547/94451043-3f210d00-01ae-11eb-87de-8d5de55f2e6b.png)

**Comment by tuarua** [comment]
It is not clear from your screen grabs above the problem you are mentioning.
The examples are scaling correctly for me and are set-up for HiDPI support.

Please provide the exact code you are using (including the app-xml)

**Comment by lgignoud** [comment]
Hi Tuara,
I finally find some time to dig into this issue.
It seems related to the "DPI Awareness" of the application. You can see this in the task manager, with those instructions:
https://winaero.com/see-dpi-awareness-task-manager-windows-10/

Steps to reproduce:
If I launch the AIR app WITHOUT creating the webview at the beginning, and with a scale factor != 100%: The DPI Awareness of the app is "unavailable".
As soon as the WebView is created, the whole AIR app DPI Awarness becomes "system" and the webview Cef subprocesses are "Per monitor". This cause some unexpected visual results.

The only workaround I found is to manually change the DPI settings of the app as explained here:
https://www.windowscentral.com/how-change-high-dpi-settings-classic-apps-windows-10-april-2018-update

But it's an extra step for the user, and one must do it again when upgrading the app.

Hope this help...

Amazing ANE by the way !

**Comment by tuarua** [comment]
Latest version 2.13.0 now uses a different Windows GetScaleFactor method which should be more reliable 
You will also need to upgrade to [FreSharp 2.5.0](https://github.com/tuarua/FreSharp/releases/tag/2.5.0)

**Comment by tuarua** [comment]
Closing assumed fixed
