### ISSUE TITLE
popup screen (window.open) issues

### ISSUE THREAD

**Issue by ryoma0906** [tuarua/WebViewANE#264]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    yes. I read wiki, FAQ and asdoc. I also run examples.
    
- **What version of the product are you using?**
    2.11

- **On what operating system?**
    Windows10
    
- **If Windows is the AIR app **32bit** or **64bit**?
    64bit

- **Which IDE are you using?**
    Flash Builder

- **Which version of AIR are you using?**
    32

- **What steps will reproduce the problem?**
    Thank you so much for developing this useful ANE. I have some questions about popup screen.
    1.can I change popup screen size after initialize?
      I can set popup screen default size by [settings.popup.dimensions.width(or height)]
      but when I call window.open, windowfeature(width, height or other features) is ignored. (also window.resizeTo is ignored).
      can I change popup screen size after initialize?

    2.can I close all popups when webview.visible = false ?
      when I call [webView.dispose()], all popups can close.
      I want to close all popups when webView hiding by [webview.visible = false.]
     can I close all popups when webview.visible = false ?

    I can't find how to fix this probrem from wiki, Faq, examples. is that impossible on this ANE?
    
    Thank you for reading

**Comment by tuarua** [comment]
1. I will need to make some changes to support the windowFeatures params of window.open() This will be available in the next version
2. You will need to track any windows you create and close them yourself. Tying this to .visible true/false is outside the remit of the webview code (remember your desired behaviour is not what others might expect)
See the example for how to communicate between AS3 and JS.

**Comment by ryoma0906** [comment]
Thank you for your comment!
1. I'm waiting for next version. and I'm hoping that your job goes well.

2.I understand your advice. I will read examples again and try it.

**Comment by ryoma0906** [comment]
Dear tuarua

I sponsored you. please have a cup of coffee.

and I need your support.
I'm facing a problem about Windows 10 scaling setting.
(This problem is similar to issues#263)

how do I get your support as a sponsor?
writing a new issue?
comment on #263?
send e-mail to you?

I'm waiting for your response.
thank you.

**Comment by tuarua** [comment]
Hi Ryoma,
Thanks for the sponsorship.
You can send an email to info@tuarua.co.uk with the details and I will reply there.

**Comment by ryoma0906** [comment]
I see. I will send you email later.

**Comment by ryoma0906** [comment]
Everything goes well.
I really appreciate your update.
