### ISSUE TITLE
How to enable WebRTC (access camera and microphone)

### ISSUE THREAD

**Issue by jasonJamEther** [tuarua/WebViewANE#271]
I am trying to access a website that requests access to the webcam. When I load the page I never see the prompt to give access and so the webcam will never work. I am trying this mainly on Windows and Mac but I do intend to do it on ios and Android too. Is this possible?

**Comment by tuarua** [comment]
Assuming you are talking about Windows Chromium version

From what I found on Google search camera + microphone can be enabled like this:

```
settings.cef.commandLineArgs.push({
    key: "enable-media-stream",
    value: "1"
});
```

https://ourcodeworld.com/articles/read/425/how-to-enable-webrtc-access-camera-and-microphone-for-cefsharp-in-winforms
https://stackoverflow.com/questions/23807343/cefsharp-and-video-tag-webrtc

**Comment by jasonJamEther** [comment]
Thanks for your help. Looks like you are right and that it is just not supported even natively yet.
