### ISSUE TITLE
Run the application(exe) with administrator privileges, the webview does not work

### ISSUE THREAD

**Issue by koreaflash** [tuarua/WebViewANE#273]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    Yes
- **What version of the product are you using?**
    - What version are you using?
    2.14.0

- **On what operating system?**
    Win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
    32bit

- **Which IDE are you using?**
    Flash Builder

- **Which version of AIR are you using?**
    31.0

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
     I exported as signed application with captive runtime.
     If you run the application(exe) with administrator privileges, the webview does not work.
     This is a phenomenon that only appears when I set the engine to 1.
     I have to set the engine to 1 for mp4 playback.
     When the engine setting is set to 0, there is no problem, but mp4 video cannot be played.

- **What is the expected output? What do you see instead?**
    When the engine is set to 1, the web view should run normally when running the app with administrator privileges.
- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.
    var settings:Settings = new Settings();
   settings.engine=1;
    webView = WebView.shared();
- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
  Yes

**Comment by tuarua** [comment]
This is likely a limitation of the Microsoft WebView1
The Edge WebView Engine is now deprecated as WebView1 is no longer supported by Microsoft. They are not fixing any issues or adding anything new to it.

See here for details on acquiring a version of the ANE which supports mp4 for Chromium WebView
https://github.com/tuarua/WebViewANE/wiki/Troubleshooting---FAQs#why-cant-i-play-mp4s-using-windows-chromium-version
