### ISSUE TITLE
Keyboard Shortcuts do not work in Mac (copy, paste, etc)

### ISSUE THREAD

**Issue by wverhoeven** [tuarua/WebViewANE#276]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
2.15.0

- **On what operating system?**
OSX
    
- **If Windows is the AIR app **32bit** or **64bit**?

- **Which IDE are you using?**
Flash Builder

- **Which version of AIR are you using?**
32

- **What steps will reproduce the problem?**
1. Click editable field in web view
2. Press Cmd-v
3. Nothing is pasted

- **What is the expected output? What do you see instead?**
None of the standard keyboard shortcuts seem to work. It is possible to access the clipboard via ctrl-click.

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
Yes

**Comment by tuarua** [comment]
Added handling for cut, copy, paste to WKWebView

**Comment by wverhoeven** [comment]
Cut, copy, paste are working in the main webview, but not working in new windows.

**Comment by tuarua** [comment]
I am still investigating a reliable solution which will work for the main and child windows.
Unfortunately Apple's WKWebview doesn't implement these keyboard shortcuts so I have to add workaround code and it's not straight forward as it needs to not interfere with AIR's keyboard shortcuts.

**Comment by tuarua** [comment]
See 2.17.0
Should now be fixed for all types of window
