### ISSUE TITLE
Make getUserMedia work | Android

### ISSUE THREAD

**Issue by Karaptor** [tuarua/WebViewANE#28]
When I try the getUserMedia function at navigator, it always returns NavigatorUserMediaError - PermissiondeniedError. No matter what I do with android permissions.

I googled around, and found similar issue at electron's webview.
https://github.com/electron/electron/issues/845

Can we have this somehow work, then logically webRTC would be available @droid using the ANE.
Thanks for all!

**Comment by tuarua** [comment]
For my own reference
http://www.flapjacksandcode.com/blog/2015/2/17/android-webviews-getusermedia-putting-it-all-together

**Comment by Karaptor** [comment]
Thanks for ur hard work on this extension!
Hopefully I can do a donation soon.

**Comment by tuarua** [comment]
There might be a few more kinks to iron out and missing features with the Android version.
Keep adding bugs/feature requests and I'll get to them when time permits.

**Comment by born2net** [comment]
I also appreciate it, I did a donation today and hope to do more donations in the future!
regards

Sean.

**Comment by tuarua** [comment]
Hi Sean, yes I saw that. It's greatly appreciated !

**Comment by born2net** [comment]
no, thank you!!!!!!!!!!!!

**Comment by Karaptor** [comment]
@_native_library\android\WebViewANE\app\src\main\java\com\tuarua\WebViewANEContext.java_
`import android.webkit.PermissionRequest;`
then after line 
`webView.setWebChromeClient(new WebChromeClient() {`
we need to add:
```
@Override
public void onPermissionRequest(final PermissionRequest request) {
  request.grant(request.getResources());
}
```

**Comment by tuarua** [comment]
Have you tried this code and does it work for you ?
It was crashing for me until I removed
super.onPermissionRequest(request); which I've removed now.

Do you have a basic HTML page which I can use to test webRTC

**Comment by Karaptor** [comment]
Yes it works well here. I will cook a public test page for you.
Btw since that I already added geolocation support, and default platform
too.
Thanks to the build scripts, and ur work ofc!
One thing I m struggling is to get file inputs working... Can u investigate?


2017. ápr. 4. 20:08 ezt írta ("Tua Rua" <notifications@github.com>):

Have you tried this code and does it work for you ?
It was crashing for me until I removed
super.onPermissionRequest(request); which I've removed now.

Do you have a basic HTML page which I can use to test webRTC

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tuarua/WebViewANE/issues/28#issuecomment-291584639>,
or mute
the thread

**Comment by Karaptor** [comment]
Just got in mind, you may test it with https://appr.tc also

2017. ápr. 4. 20:16 ezt írta ("Kisraptor Erős" <lenovokisraptor@gmail.com>):

**Comment by tuarua** [comment]
Are you able to create a Fork / branch with your updates? I could do a pull request if it all looks good

**Comment by tuarua** [comment]
Here is Google's file input example
https://github.com/GoogleChrome/chromium-webview-samples/tree/b18afa96ab6215eed526c19156bf0fe6f5386ad1/input-file-example

Looks quite involved. May take a while

**Comment by tuarua** [comment]
Marking this as closed. Will add file input to a separate ticket

**Comment by tuarua** [comment]
btw request.grant(request.getResources()); only seems to work when the project is compiled < 24.
I have tried other web view ANEs and they have the same problem. I imagine it's due to the permission changes in Android 6+
