### ISSUE TITLE
Can't connect localhost when I set 'settings.engine = WebEngine.EDGE;'

### ISSUE THREAD

**Issue by code5381** [tuarua/WebViewANE#280]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
      2.17.0

- **On what operating system?**
    - Win10 (10.0.19042 N/A build 19042)
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - 64bit

- **Which IDE are you using?**
    -Flash Builder, cmd line

- **Which version of AIR are you using?**
    - 30

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
    
      ****Can't connect localhost when I set 'settings.engine = WebEngine.EDGE;'****
 
- **What is the expected output? What do you see instead?**
      Expect to connect localhost site.

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.
       result: http://localhost:8888/tabTest2.html
                404
                NotFound
                0
- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
    Yes

Thanks in advanced.

Kevin.

**Comment by tuarua** [comment]
The Edge WebView doesn't support `localhost` without running your app with loopback exemptions
https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/2226#issuecomment-396360314

Besides that, The Edge engine based on MS WebView1 is no longer supported.

**Comment by tuarua** [comment]
If you are using Edge WebView to be able to play mp4 H.264 video, then I offer a privately distributed WebViewANE version which supports proprietary codecs. It is not free, so please contact me to further discuss.

https://github.com/tuarua/WebViewANE/wiki/Troubleshooting---FAQs#why-cant-i-play-mp4s-using-windows-chromium-version.

Closing as EdgeWebView is no longer supported
