### ISSUE TITLE
Unable to sign Adobe Air Framework on MacOS Big Sur using sign_developerId.sh script

### ISSUE THREAD

**Issue by daghendrik** [tuarua/WebViewANE#281]
- **What version of the product are you using?**
    - 2.17.0

- **On what operating system?**
    - OSX Big Sur 11.2.1
    
- **Which IDE are you using?**
    - IntelliJ
    
- **Which version of AIR are you using?**
    - 32

- **What steps will reproduce the problem?**
   - Running bash sign_developerId.sh
   
- **What is the expected output? What do you see instead?**
   - MyApp.app/Contents/Frameworks/Adobe AIR.framework/Adobe AIR: bundle format is ambiguous (could be app or framework)

- **Please provide any additional information below.**
    - The script to sign the .app file (after creating a captive runtime bundle in IntelliJ) doesn't seem to work after upgrading to Big Sur. It fails with "Failed to sign AIR Framework: 1" and the more detailed message "Adobe AIR.framework/Adobe AIR: bundle format is ambiguous (could be app or framework)". Separately signing individual files seem to work.
    - The error occurs on line 184 in https://github.com/tuarua/WebViewANE/blob/master/mac_installer/sign_developerId.sh

**Comment by tuarua** [comment]
I am not having any such problems.
Using Bug Sur 11.2.3 on Intel Xeon iMac
Tried both latest Harman AIR 33.1.1.444 and Adobe 32.0.0.116

Make sure your SDK/Adobe AIR.framework is not quarantined (run your app debug or unsigned .app first)

**Comment by daghendrik** [comment]
I think running it in debug might have helped. I also tried manually fixing symlinks. Either way, I finally got it signed and successfully notarized. Thanks for your help and quick reply. Your open source repos are awesome!

**Comment by daghendrik** [comment]
To be a bit more precise: I added these lines to your [script](https://github.com/tuarua/WebViewANE/blob/master/mac_installer/sign_developerId.sh) and successfully notarized for AIR 32.0.0.116 :

```
echo ${cyn} "Fixing Symlinks" ${white}
cd "$APP.app/Contents/Frameworks/Adobe AIR.framework"
rm "Adobe AIR"
ln -s "Versions/Current/Adobe AIR" "Adobe AIR"
ln -s "Versions/Current/Adobe AIR_64" "Adobe AIR_64"
rm -fr "Resources/"
ln -s "Versions/Current/Resources" "Resources"
cd "Versions/"
rm -fr "Current"
ln -s "1.0" "Current"
cd "$pathtome"
xattr -cr $APP.app
```
