### ISSUE TITLE
When loading local HTML, if Korean is included in the path, it is not loaded.

### ISSUE THREAD

**Issue by koreaflash** [tuarua/WebViewANE#286]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
e.g. 2.15.0

- **On what operating system?**
    - Win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit

- **Which IDE are you using?**
    - Flash Builder4.7

- **Which version of AIR are you using?**
    - 29

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
    - As in the URL below, if Korean is included in the path, html cannot be loaded.
       The Users folder index is displayed as shown in the attached image.
      "file://C:\Users\정한솔 정한샘\AppData\Roaming\com.visang.englisheye.desktop\Local Store\player\index.html"
![capture](https://user-images.githubusercontent.com/36652089/121450873-7f8c8800-c9d7-11eb-9248-eb43619e0dea.png)
- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
- yes

**Comment by koreaflash** [comment]
After encoding using encodeURI(), it is loaded normally.
Is it correct to use like this?

**Comment by tuarua** [comment]
Use the correct method for loading local files `webView.loadFileURL`

eg. the following works OK for me

```
var localHTML:File = File.applicationDirectory.resolvePath("정한솔 정한샘/jsTest.html");
webView.loadFileURL(localHTML.nativePath, File.applicationDirectory.nativePath);
```

Do not prepend `file://`
Do not use `encodeUri`

**Comment by koreaflash** [comment]
I tried as below, but it doesn't load normally.
If you use a path that includes Korean, it doesn't seem to work properly.

var playerFile:File = File.applicationDirectory.resolvePath("이승호/index.html");
webview.loadFileURL(playerFile.nativePath, File.applicationDirectory.nativePath);

var playerFile:File = File.applicationDirectory.resolvePath("이승호/index.html");
webview.load(new URLRequest(playerFile.nativePath));

playerFile.nativePath 
E:\works\_project_visang\project\EnglishEye_elementary\EnglishEye_etri_8_desktop\bin-debug\이승호\index.html
![capture1](https://user-images.githubusercontent.com/36652089/121613855-6566ae80-ca98-11eb-895d-3dbb576aa583.JPG)

**Comment by koreaflash** [comment]
Regardless of loadFileURL() or load(), if Korean is included in the url, the above phenomenon occurs.
The url is loaded normally only after encodeURI as shown below.
http://test.dmook.co.kr/test/shlee/이승호 테스트/apk_down.html
=> http://test.dmook.co.kr/test/shlee/%EC%9D%B4%EC%8A%B9%ED%98%B8%20%ED%85%8C%EC%8A%A4%ED%8A%B8/apk_down.html

**Comment by tuarua** [comment]
I was still not able to reproduce. My system is set to English not Korean.
strings **must** be passed to ANEs in UTF-8 format. The default language and encoding on your system may be something other than UTF-8 and resulting in this quirk.

You will likely have to use uriEncode if your system is not UTF-8
