### ISSUE TITLE
Windows installer Dotnet Runtime download URL 404

### ISSUE THREAD

**Issue by johnwu** [tuarua/WebViewANE#289]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
    - Happens with all versions

- **On what operating system?**
    - Win7
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - Both

- **Which IDE are you using?**
    -All

- **Which version of AIR are you using?**
    - All

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.

The Inno Setup scripts for downloading the Dotnet runtime results in a 404 error. Microsoft has removed the file from the URL http://download.microsoft.com/download/D/5/C/D5C98AB0-35CC-45D9-9BA5-B18256BA2AE6/NDP462-KB3151802-Web.exe

Does anyone have an alternative download URL?

- **What is the expected output? What do you see instead?**

No 404 error running the Inno Setup installer

**Comment by tuarua** [comment]
try https://go.microsoft.com/fwlink/?linkid=780596
as per
https://github.com/DomGries/InnoDependencyInstaller/blob/master/CodeDependencies.iss

I have updated the iss

**Comment by johnwu** [comment]
Thanks you. That url worked !
