### ISSUE TITLE
 Apple M1: Error #3500: The extension context does not have a method with the name init.

### ISSUE THREAD

**Issue by aW4KeNiNG** [tuarua/WebViewANE#292]
- **What version of the product are you using?**
2.21.0

- **On what operating system?**
Mac

- **Which version of AIR are you using?**
33.1.1.633

- **What steps will reproduce the problem?**

Using the next initialization code in my app:

```
var settings:Settings = new Settings();
settings.useHiDPI = false;
_webView = WebView.shared();
_webView.init(FlexGlobals.topLevelApplication.stage, viewPort, null, settings, 1.0, 0x000000);
```

some users are getting the next error on Mac (2 users with MacOS 12 and 1 with MacOs 11.5)

```
Error Message: Error #3500: The extension context does not have a method with the name init.
Trace: ArgumentError: Error #3500: The extension context does not have a method with the name init.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.tuarua::WebView/init()[/Users/eoinlandy/flash/WebViewANE/native_extension/src/com/tuarua/WebView.as:98]
```

I can't replicate it because the issue doesn't happen to me (MacOS 11.6). Windows version is working fine too.

Any ideas?

**Comment by aW4KeNiNG** [comment]
Could it be something related to Apple M1? All of them have M1.

**Comment by tuarua** [comment]
Yes that is the reason. M1 use arm64 chips and the ANE is intel only currently.

I will be looking into support of M1 in the coming weeks.

**Comment by tuarua** [comment]
2.23.0 now has arm64 to support M1
N.B. You will also have to update to FreSwift `5.5.1` and I believe AIR SDK has to be .633

**Comment by aW4KeNiNG** [comment]
It works :)
