### ISSUE TITLE
FreTypeMismatch 

### ISSUE THREAD

**Issue by koreaflash** [tuarua/WebViewANE#295]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
    => WebViewANE-H264-AAC_2.19.0 / FreSharp_2.5.0

- **On what operating system?**
    - OSX, Win7, Win 8, Win10, etc?
    => Windows 10 64bit

- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit or 64bit
    => 32bit
    

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?
    - Flash Builder 4.7

- **Which version of AIR are you using?**
    - 29,30.. etc?
    => 29.0.0.122

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
    => During debugging, the following message is displayed in the console window.
    => [WebViewANE] [FreSharp] ‼ FreTypeMismatch cannot get FREObject  as String

- **What is the expected output? What do you see instead?**
   => What does the above message mean?
- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**

**Comment by tuarua** [comment]
Please provide full details and steps to reproduce.

**Comment by koreaflash** [comment]
내 생각에는 동영상 콘텐츠가 포함된 웹페이지를 로드할 때만 나타나는 것으로 판단됩니다.

동영상 콘텐츠 재생을 위한 HTML페이지를 로컬(File.applicationStorageDirectory) 에 복사한 후 사용합니다.

src 값은 아래와 같습니다.
C:/Users/myuser/AppData/Roaming/appid/Local%20Store/player/
 index.html?device=desktop&video=https://mycontents.com/fileRoot/multimedia/202008/PW.ExLect.
 1B.U4.L4.mp4&bmove=y&bspeed=y&bctrlpos=y

loadFileURL(src, null)을 호출 후 콘솔 창에 아래 메시지가 표시 됩니다.
[WebViewANE] [FreSharp] ‼ FreTypeMismatch cannot get FREObject  as String

# load() 메소드를 사용하면 위의 메시지가 나오지 않습니다.
# loadFileURL() 메소드를 사용하는 이유는 : https://github.com/tuarua/WebViewANE/issues/286#issuecomment-859014137

#동작에는 문제가 없어보입니다. 그러나 그 메시지가 무슨 의미인지 궁금합니다.

**Comment by tuarua** [comment]
You are passing `null `as param 2. It expects a `String`. which is why it says "Type Mismatch"

use `File.applicationStorageDirectory.nativePath` for param 2
