### ISSUE TITLE
A way to track errors

### ISSUE THREAD

**Issue by xyrer** [tuarua/WebViewANE#30]
- **What version of the product are you using?**
0.0.18
- **On what operating system?**
Win7, Win8, win10
- **Which IDE are you using?**
IntelliJ
- **Which version of AIR are you using?**
24
- **What steps will reproduce the problem?**
Package air application, install, open.
- **What is the expected output? What do you see instead?**
Expected: browser opens and shows web page
Actual result: Application stopped working
- **Please provide any additional information below.**
There is no stack trace, that's the problem.
- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
Yes

**Comment by tuarua** [comment]
Did you follow the instructions in the README about the dependencies.
It sounds like the app is crashing because you haven't copied over the required CEF dlls

**Comment by tuarua** [comment]
This error would be in your Windows crash logs

**Comment by tuarua** [comment]
See this screenshot - it shows how the bin folder where adl.exe lives, needs to have the cef dlls.
https://raw.githubusercontent.com/tuarua/WebViewANE/master/screenshots/your-bin-folder.PNG

**Comment by tuarua** [comment]
If you are packaging in IntelliJ, you also need to have these files in the same folder as the output exe.
Have a look through the closed tickets also. Others faced the same stumbling block.

**Comment by xyrer** [comment]
It doesn't fail at all on the developing machine. While developing it works ok, installing the release version it works ok. Tested on another computer, win10, installed the distributable libraries, it crashes. Tried on Win8, same thing happens.

**Comment by xyrer** [comment]
Application: WebViewANESample.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: exception code c0000005, exception address 647CE8A9 Stack:

**Comment by xyrer** [comment]
My App keeps failing with exception c0000005 as logged on Windows event viewer, the example doesn't but both installers have same files included, tested on the same computer. any idea of where should I try to control the error and see a little more detail?

**Comment by tuarua** [comment]
Can you post an example project which exhibits the problem.

**Comment by xyrer** [comment]
Well, yeah, the problem is that same project doesn't fail on my machine. I'll gather an example and post anyway.

**Comment by tuarua** [comment]
Can you clarify.
The GitHub sample works but
Your app doesn't work ?
Your app works on your machine but not another ?

**Comment by xyrer** [comment]
That's exactly it. My app works fine on my machine, so does the github example.
example works on another machine, mine doesn't on that same machine, even trying to use the same relevant code.

**Comment by tuarua** [comment]
That's weird. Your app, how is it different to the example?
Eg is it not using Starling, using Flex different AIR SDK non captive runtime etc etc

**Comment by xyrer** [comment]
It's starling also, last version from github, using air sdk 24, deafult .exe intellij Build. I Made a barebones example without starling and it doesn't fail, So I will have to  keep adding to it until I find the culprit, that's why I was asking for a way to catch the real reason because it must be some conflict with what I have but I'm having to do trial and error, which is painfully time expensive.

**Comment by tuarua** [comment]
Did you solve this problem ?

**Comment by xyrer** [comment]
Kind of, It seems to be a problem with not having enough memory, I was creating a slide with videos and I had to remove it and that avoided the problem. I wonder if there's something lacking in .net to let me know the exact reason of the problem.

**Comment by tuarua** [comment]
It's not a .NET problem.

You can set settings.cef. logSeverity https://github.com/tuarua/WebViewANE/blob/master/native_extension/src/com/tuarua/webview/CefSettings.as#L35

This will write out CEF logs to the win console, so you have to debug using adl from the command line.
Generally though, I have no plans to add crashlytics style reporting. How users of the ANE write their apps is up to them.

**Comment by xyrer** [comment]
Well, the logs will have to do. Thanks a lot.
