### ISSUE TITLE
addCallback("jsFunctionName", asFunction) - errors cannot be catched at asFunction by AIR Debug Launcher

### ISSUE THREAD

**Issue by ylazy** [tuarua/WebViewANE#301]
- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Yes
    
- **What version of the product are you using?**
    - What version are you using?
2.24.0

- **On what operating system?**
    - Win 11
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit

- **Which IDE are you using?**
    - Animate, Flash Develop

- **Which version of AIR are you using?**
    - 32, 33

- **What steps will reproduce the problem?**

```
_webView.addCallback("jsFunctionName", asFunction);

function asFunction(input:ActionscriptCallback):void
{
// if there are any errors here, they cannot be caught by the AIR Debug Launcher.
// instead, there're error traces on the Output panel, but there aren't any line number or class name information, like this:
// Error #1010: A term is undefined and has no properties.
}
```

**Comment by tuarua** [comment]
The error is caught inside the ANE AS code. So is working correctly.
https://github.com/tuarua/WebViewANE/blob/e6f5f7dbf35c59f06daa7703a29bd95c9aecf74c/native_extension/src/com/tuarua/WebViewANEContext.as#L164

The problems is likely down to you not implementing the message from JS > AS properly.
See the examples.
https://github.com/tuarua/WebViewANE/blob/e6f5f7dbf35c59f06daa7703a29bd95c9aecf74c/example-desktop-complete/src/jsTest.html#L41

I have to close as this is not a bug with the ANE
