### ISSUE TITLE
The DownloadProgress .percent return wrong value (0 instead of -1) when the receive total size is unknown

### ISSUE THREAD

**Issue by ylazy** [tuarua/WebViewANE#306]
- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - yes
    
- **What version of the product are you using?**
    - 2.27.0

- **On what operating system?**
    - Win11
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - 64bit

- **Which IDE are you using?**
    - VSCode

- **Which version of AIR are you using?**
    - 50.1.1.2

- **What steps will reproduce the problem?**
    - The [DownloadProgress percent](https://tuarua.github.io/asdocs/webviewane/com/tuarua/webview/DownloadProgress.html#percent) return `0` instead of `-1` when the receive total size is unknown. Because the current type of the `percent` property is `uint`. It should be `int`

- **What is the expected output? What do you see instead?**
   - Expected value: `-1`
   - Actual value: `0`

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
   - no

**Comment by tuarua** [comment]
Should be fixed in 2.28.0

**Comment by ylazy** [comment]
Fixed! Thank you!
