### ISSUE TITLE
ANE Crashes in FlashBuilder Flex-Project

### ISSUE THREAD

**Issue by dantiel** [tuarua/WebViewANE#33]
I put the cef binaries and libraries in the bin folders of the flex/air-framework, but still I keep getting this error.

- **What version of the product are you using?**
0.0.14

- **On what operating system?**
Win7

- **Which IDE are you using?**
Flash Builder

- **Which version of AIR are you using?**
Flex 4.15 / Air 23

- **What steps will reproduce the problem?**
Start App / Initialize ANE. It crashes right after `ExtensionContext.createExtensionContext` is run.

- **What is the expected output? What do you see instead?**
 -

- **Please provide any additional information below.**
Beschreibung:
  Stopped working

Problemsignatur:
  Problemereignisname:	APPCRASH
  Application Name:	adl.exe
  Application Version:	23.0.0.257
  Application Timestamp:	57c5e9f7
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.17514
  Fault Module Timestamp:	4ce7b8f0
  Exception Code:	e0434f4d
  Exception Offset:	0000b760
  Betriebsystemversion:	6.1.7601.2.1.0.256.1
  Gebietsschema-ID:	1031

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
The sample Application doesn't run in FlashBuilder as theres no option select another Air-Version than 3.4 for Actionscript-Projects.

**Comment by tuarua** [comment]
And have you followed the rest of the instructions about ensuring you have these 2 also installed ?
Visual C++ 2015 Redistributable (x86)
Visual C++ 2013 Redistributable (x86)

**Comment by dantiel** [comment]
yes i checked again and both of them are installed.

**Comment by tuarua** [comment]
What version of .NET is on your Windows 7 machine ?
The ANE requires 4.5.2 and above

**Comment by tuarua** [comment]
Closing due to lack of response
