### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by leefj** [tuarua/WebViewANE#43]
Hi, will this support WebAssembly?

**Comment by tuarua** [comment]
WebAssembly runs fine on Windows version, as it is essentially Chromium 57.
http://webassembly.org/demo/Tanks/

I can't check if the mac version does as I am not near my mac.

**Comment by tuarua** [comment]
WebAssembley will be supported in Safari 11 and so will be supported by WKWebview which the OSX + iOS version uses. Safari 11 is due in autumn
