### ISSUE TITLE
Blocked Popup - catch Touch-event

### ISSUE THREAD

**Issue by berlinMilo** [tuarua/WebViewANE#45]
- Version: WebViewANE v. 0.0.21
- OS: Win 8 / Desktop / Touch
- IDE: - FDT
- AIR: - 22
- Problem:
- embedding GoogleMaps in the WebViewANE.
- PopUps are blocked.
- Now click multiple times on an external PopUp-Link - "Google" in the lower left corner.

- Output:
- Touches are watched by Chromium. No more reaction on touches in the AIR-App.
- To clear, i have to use a Mouse-click one time.

How can i debug this.
My developing machine has no touch.

Yours -milo

**Comment by berlinMilo** [comment]
- Sorry: the Chromium **catches** the touch-events.
- you have to touch quite fast an the popup-link.

**Comment by tuarua** [comment]
To test touch on a desktop you use Microsoft Windows Simulator. It is provided with Visual Studio Community or Full edition.
C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Simulator\14.0\Microsoft.Windows.Simulator.exe

Have a look in jsTest.html and StarlingRoot.as. There is a focus workaround which affects text inputs on touch devices also.

```
//workaround for Windows touch, ensures the webview is focussed on
        window.addEventListener("load", function () { // on page load
            document.body.addEventListener("touchend", function (e) {
                var messageToPost = {
                    'functionName': 'forceWebViewFocus',
                    'callbackName': null,
                    'args': []
                };
                getWebviewANE().postMessage(messageToPost);
            }, false)

        }, false)
```

**Comment by berlinMilo** [comment]
The focus workaround does not work.
No workaround like virtual mouseClicks seems to work.
No touch-connected cf-settings had any effect on the behaviour.
No fix in sight?
-milo

**Comment by tuarua** [comment]
I didn't look at this as high importance because you said "you have to touch quite fast an the popup-link" - which suggested it was an edge case bug, and something you would have to intentionally produce. If you are saying it is easy to cause and occurs often then I will have a look.

**Comment by berlinMilo** [comment]
It's running in in POI-Terminal with a lot of bored teenagers as "customers". They find every bug!
So a fix would be necessary and very appreciated. Thanks for looking into it.

**Comment by tuarua** [comment]
I have added a new Event ON_POPUP_BLOCKED.
To prevent touch trap call this when the event triggers
`Starling.current.nativeStage.dispatchEvent(new MouseEvent(MouseEvent.CLICK)); `
Please see updated example.

**Comment by tuarua** [comment]
Closing. Assumed as fixed.
