### ISSUE TITLE
How to get the following property (window.document...) from webview?

### ISSUE THREAD

**Issue by lucasreisprestes** [tuarua/WebViewANE#50]
How to get the following property (window.document.title) from webview?

I need to invoke a virtual keyboard embedded in my as3 app.

Exemple: [http://help.adobe.com/pt_BR/FlashPlatform/reference/actionscript/3/flash/html/HTMLLoader.html#htmlHost](url)

**Comment by tuarua** [comment]
Please study the example that is provided with the ANE, It demonstrates well all the functionality available including events for when title is updated and how to call javascript code from as3
