### ISSUE TITLE
Long Press text selection  Windows touch - Known CEF issue

### ISSUE THREAD

**Issue by tuarua** [tuarua/WebViewANE#53]
Long pressing on text selection causes a crash on Windows 10 touch devices.
This is a bug in CEF 57.
CefSharp and indeed the CEF dist packages are released every 2nd version of Chromium.
It is currently on CEF v57 so when v59 is released it will be incorporated.
This usually occurs within a couple of weeks. 59 is due to be released sometime in June.
In the interim:
You can disable long press in under System > Pen and Touch

**Comment by salesbuddy** [comment]
Has there been any progress on this? I desperately need a fix. Even when I disable log press through Pen and Touch this happens.

**Comment by tuarua** [comment]
This is dependant on CefSharp. 
It was a bug fixed in Chromium Embedded Framework 58
CefSharp is stuck on 57 because CEF 58 changed a fundamental part and it means it would break JS if CefSharp upgrades. It is being actively looked into by their contributors. As soon as CefSharp is updated I will update the ANE.

You can watch this ticket.
https://github.com/cefsharp/CefSharp/issues/1203

**Comment by salesbuddy** [comment]
Thank you for your quick reply.

**Comment by tuarua** [comment]
CefSharp is soon to be updated to CEF 63 which will resolve this.
https://github.com/cefsharp/CefSharp/issues/2234

**Comment by tuarua** [comment]
This is now fixed in 1.3.0
