### ISSUE TITLE
It's possible?

### ISSUE THREAD

**Issue by lucasreisprestes** [tuarua/WebViewANE#57]
My question may be answered, but I want to confirm if in any way
I can work around the problem:

'"Inside my app I have two buttons for two screens, the first one
I want to open an X site. Returning to the menu,
Should remove it from the stage, I want to load another site. "

It's possible?

**Comment by tuarua** [comment]
I don't understand what you mean.
Can you provide a visual representation of what you are trying to do.
The webview is just like a browser.
You use the loadUrl() method to load different pages.

Also, the issues section is mostly for issues / bugs or to suggest features.

**Comment by tuarua** [comment]
Closing as no response received
