### ISSUE TITLE
unzip cef_binaries.zip error 

### ISSUE THREAD

**Issue by ganxunzou** [tuarua/WebViewANE#6]
unzip cef_binaries.zip error 
Look like :
![2017-01-17_213315](https://cloud.githubusercontent.com/assets/5092728/22022380/b766d914-dcfc-11e6-847f-886773e7871a.png)

**Comment by tuarua** [comment]
Zip download failed
Try downloading directly in your browser
https://github.com/tuarua/WebViewANE/raw/master/cef_binaries.zip
