### ISSUE TITLE
can not display webview content on Android

### ISSUE THREAD

**Issue by nidiy** [tuarua/WebViewANE#63]
![image](https://oityq0cxd.qnssl.com/2017-07-14_59687e542b9f6.jpg?e=1500023921&token=-YdeH6WvESHZKz-yUzWjO-uVV6A7oVrCN3UXi48F:XZElVSAyKKi0CKv_fIqb1nL2MRU=)

I use your demo Example

#61

**Comment by tuarua** [comment]
This should now be fixed on master

**Comment by nidiy** [comment]
@tuarua  Now normal, thank you

**Comment by tuarua** [comment]
no problem
