### ISSUE TITLE
Initalizing ANE..  Issue

### ISSUE THREAD

**Issue by Simon-wu** [tuarua/WebViewANE#70]
- **Have you read the README carefully?**
 Yes  i read it  and  Install all 
    
- **What version of the product are you using?**
e.g. 0.0.28

- **On what operating system?**
     win 10
    
- **If Windows is it?**
       64bit

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?
 use  Flash Builder

- **Which version of AIR are you using?**
    air sdk 26 32bit

- **What steps will reproduce the problem?**
I try use you example, and found ane in WebViewANE-master\native_extension\ane  folder 
Launch the adl  , console print [WebViewANE] Initalizing ANE...   A few seconds the process exit,

- **What is the expected output? What do you see instead?**
CommonDependencies.ane not for win the IDE tips , but i can not find other
 [http://i1.bvimg.com/1949/f18e17e5f5a3edb7.png](url)
[http://i1.bvimg.com/1949/d5124983ee2d15ca.png](url)
[http://i1.bvimg.com/1949/3dac8411e62032f9.png](url)

- **Please provide any additional information below.**
  [http://i1.bvimg.com/1949/f18e17e5f5a3edb7.png](url)
[http://i1.bvimg.com/1949/d5124983ee2d15ca.png](url)
[http://i1.bvimg.com/1949/3dac8411e62032f9.png](url)
[](http://i1.bvimg.com/1949/3dac8411e62032f9.png)

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
Yes

**Comment by tuarua** [comment]
You say you are using Windows64bit and AIRSDK 26 32bit.

Therefore you need to use the dlll files in https://github.com/tuarua/WebViewANE/tree/master/cef_sharp_libs_x86
and
https://github.com/tuarua/WebViewANE/releases/download/0.0.28/cef_binaries_x86.zip

**Comment by tuarua** [comment]
Ignore http://i1.bvimg.com/1949/d5124983ee2d15ca.png - this is ok. Common Dependencies is mac only. Ignored on windows.
http://i1.bvimg.com/1949/3dac8411e62032f9.png - this error is important. It suggests the CEF dlls or project dlls are not in the correct place or wrong architecture

**Comment by Simon-wu** [comment]
@tuarua <img src="https://user-images.githubusercontent.com/12083217/28994431-e9b3da78-79c5-11e7-8b4b-337230d25bd6.png" alt="image" style="max-width:100%;">
this image  is Very useful ， I  found the issue  https://github.com/tuarua/WebViewANE/tree/master/cef_sharp_libs_x86
this dll has not put in bin folder 
 because cef_binaries_x86.zip  and cef_sharp_libs_x86  like same   i'm vertigo

thank very much
