### ISSUE TITLE
Run  issue

### ISSUE THREAD

**Issue by Simon-wu** [tuarua/WebViewANE#72]
- **What version of the product are you using?**

e.g. 0.0.28

- **On what operating system?**
    - Win10
    
- **If Windows is it?**
    -  64bit

- **Which IDE are you using?**
    -  Flash Builder,

- **Which version of AIR are you using?**
    - 26  32bit

- **What steps will reproduce the problem?**
    some times  on launch  or I click html  element  the air force close

- **What is the expected output? What do you see instead?**
<img src='http://i1.bvimg.com/1949/2b96bd7e48766716.png'>
- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
- **Not sure

**Comment by tuarua** [comment]
That error doesn't tell me a lot.
If you can't reproduce with the sample provided, please upload a basic project which produces the error and I will have a look.

**Comment by tuarua** [comment]
no response - assuming closed
