### ISSUE TITLE
Setting viewPort width with float values cause cast convert crash

### ISSUE THREAD

**Issue by jon-reid-nz** [tuarua/WebViewANE#76]
- Ver 0.0.29
- Win10, 64bit, Flash Builder, AIR 26

Setting a viewport width with a float rather than int causes the following crash

Problem signature:

  Problem Event Name:   CLR20r3

  Problem Signature 01:   SCSReportingGen3.exe

  Problem Signature 02:   missing

  Problem Signature 03:   592be128

  Problem Signature 04:   FreSharp

  Problem Signature 05:   1.0.0.0

  Problem Signature 06:   596b9ce6

  Problem Signature 07:   41

  Problem Signature 08:   0

  Problem Signature 09:   System.InvalidCastException

  OS Version:       6.1.7601.2.1.0.256.48

  Locale ID:          5129

  Additional Information 1:            0a9e

  Additional Information 2:            0a9e372d3b4ad19135b953a78882e789

  Additional Information 3:            0a9e

  Additional Information 4:            0a9e372d3b4ad19135b953a78882e789

**Comment by tuarua** [comment]
fixed in latest version
