### ISSUE TITLE
For Windows Where is the folder AIRSDK

### ISSUE THREAD

**Issue by HiriswHe** [tuarua/WebViewANE#80]
- **Have you read the README carefully?**
    - Yes
    
- **What version of the product are you using?**
    - 0.0.30
e.g. 0.0.27

- **On what operating system?**
    - Win7
    
- **If Windows is it?**
    - 64bit

- **Which IDE are you using?**
    -Visual Studio 2015

- **Which version of AIR are you using?**
    - 20

- **What steps will reproduce the problem?**
    - On beginning

Q:

![question](https://user-images.githubusercontent.com/31640905/30043490-41834578-922a-11e7-96d3-b63d7ad2bdf3.jpg)
Where is the folder AIRSDK?

**Comment by tuarua** [comment]
The location of the AIR SDK will depend on the IDE you are using, eg Flash Builder, Intelli J, Flash Develop.

I have never heard of Visual Studio being used to build Adobe AIR apps but do a search on your computer for air-sdk-description.xml or airsdk.xml. The containing folder is the AIR SDK.
