### ISSUE TITLE
Support PC ADT package

### ISSUE THREAD

**Issue by nidiy** [tuarua/WebViewANE#83]
hi,
    Can WebViewANE now use ADT to package ipa on a PC?
    Currently on the Mac using IntelliJ IDEA packaged ipa successful.
    But still want to pack on the PC
    Is there any good advice?

**Comment by tuarua** [comment]
That depends on whether AIR 27 now supports signing dynamic frameworks with ADT on Windows also.
You can try yourself. 

Here is the Adobe ticket for reference.
https://tracker.adobe.com/#/view/AIR-4198407
