### ISSUE TITLE
Touch and  Click 

### ISSUE THREAD

**Issue by leefj** [tuarua/WebViewANE#84]
I install your ane in a windows 7 touch screen device , when i use mouse to click a link or button ,it works well ,but when i use finger to touch and tap these buttons , it seems not work;

same page both mouse click and finger touch works well in chrome browser.

can you fix this ?

**Comment by tuarua** [comment]
Windows 10 touch devices are supported and work.
I don't own a Windows 7 touch device and have no plans to investigate this.
