### ISSUE TITLE
IOS does not support multiple instances

### ISSUE THREAD

**Issue by nidiy** [tuarua/WebViewANE#85]
hi,
     v0.0.31
     In the IOS platform, when I create multiple WebView ANE instances, the first created WebView will be replaced by the URL created later? The two WebView will display the same content

**Comment by tuarua** [comment]
Like the other WebView ANEs from others multiple instances are not supported. You should only create one instance.
If you wish to load different sites you can either:
1) use frames
2) Modify the Swift code source to support multiple WKWebViews inside the ANE.

**Comment by nidiy** [comment]
Thank you for the suggestion that I am trying to modify the Swift source code.

**Comment by nidiy** [comment]
Read the source do not know how to amend the support of multiple cases, do not know if you have plans to support multiple cases?

**Comment by tuarua** [comment]
no plans at the minute
