### ISSUE TITLE
Example Screenshot please - Capture function for iOS, Android, OSX

### ISSUE THREAD

**Issue by yooni126** [tuarua/WebViewANE#88]
Hi, in mobile I would like to load my website off screen then take a screenshot 
I see you have a capture fucntion
but can you show me an example with starling codes?
FYI , when I use webView.capture(0, 0,100,200) , It send me  a null  :(

**Comment by tuarua** [comment]
The capture function is currently Windows only.
Adding to iOS, OSX and Android is on my TODO list. I was waiting for iOS 11 which has inbuilt functions for this.
Do you need for Android and iOS ?

**Comment by yooni126** [comment]
Yes, I want it for android and iOS  and I really need it
for android how long should I wait?
how about iOS?

**Comment by yooni126** [comment]
and another question : is there any way to export pdf from webview content ?

**Comment by tuarua** [comment]
3-4 weeks. I have other priorities at the moment.
The project is **Open Source**. You are free to fork it and add any features yourself.

**Comment by tuarua** [comment]
@yooni126  just to update on this - the next release with capture method for iOS and Android will be released this weekend

**Comment by yooni126** [comment]
@tuarua Thank you 👍 
Impatiently waiting...
