### ISSUE TITLE
I see an error when attach Ane to Mac project

### ISSUE THREAD

**Issue by aleksh** [tuarua/WebViewANE#91]
- **Have you read the README carefully?**
yes

    - What version are you using?
e.g. 0.0.32

- **On what operating system?**
    - OSX

- **Which IDE are you using?**
    - Flash Builder

- **Which version of AIR are you using?**
    - 26

- **What steps will reproduce the problem?**
    - When I try to add ane to project I see an error "This ANE down not support air-native-macosx platform"

- **What is the expected output? What do you see instead?**

<img width="980" alt="screen shot 2017-10-02 at 3 23 57 am" src="https://user-images.githubusercontent.com/10978167/31060771-b6a14b64-a721-11e7-8566-55ecbed90327.png">
<img width="878" alt="screen shot 2017-10-02 at 3 24 46 am" src="https://user-images.githubusercontent.com/10978167/31060776-c1b55d6a-a721-11e7-9c8e-29d8de96897f.png">

But ANE is working : )

**Comment by tuarua** [comment]
Please see the "Linking ANE using Flash Builder 4.7" section on this Adobe blog.

http://blogs.adobe.com/flashplayer/2015/12/air-64-bit-on-mac-osx.html#sthash.1R5wVhzw.dpbs

Flash Builder has some known quirks on mac with ANEs.
You need to **export a release build first** (check ignore errors)
Then you can run a debug build.

Also, build the example project first before trying to integrate into your own project.

**Comment by aleksh** [comment]
Hi 
It works

**Comment by Nisaba** [comment]
Unfortunately, it doesn't work for me : 
I've done all steps described 
When I export a release build, I can't check "Ignore errors" because this checkbox is disabled.

Any idea ?

**Comment by tuarua** [comment]
![image](https://user-images.githubusercontent.com/12083217/38327414-131aff02-3840-11e8-94fa-f5d7f56835eb.png)

**Comment by Nisaba** [comment]
Thank you for you feedback.

But here is what I get : You can see the disabled check box.
Any idea ?

![fb47](https://user-images.githubusercontent.com/34550856/38330994-59d2aa00-3852-11e8-94d5-c998cc72048c.jpg)

**Comment by tuarua** [comment]
You haven't even included the 2 ANEs by checking "Inclure dans..."
Please follow the instructions carefully and look at the pictures.

**Comment by Nisaba** [comment]
It's exactly what I want to do.
Buth the "Inclure dans..." checkboxes are aslo disabled, as you can see in the picture, and I don't know why...

**Comment by Nisaba** [comment]
Sorry,
But the ane are valid and unfortunately, I get the same problem with Flex 4.7 on a PC :
The checkbox are also disabled in the same screen...

Anyone has an idea ?

Thanks a lot

**Comment by tuarua** [comment]
Are you trying to create an AIR package?
You can't use ANEs with a .air.

You must use a Signed application with captive runtime
![image](https://user-images.githubusercontent.com/12083217/39265556-765c21e2-48bf-11e8-99e4-e42b4354c9a7.png)

**Comment by aleksh** [comment]
hi 
my fb 4.7 doesn't compile my project on mac after latest mac os updates
i moved all my projects to Intellij IDEA  and now  my project works with this ane

**Comment by Nisaba** [comment]
@tuarua 
Yes !! it works now !
Thank you very much
