### ISSUE TITLE
zoom & pan (pinch)

### ISSUE THREAD

**Issue by yooni126** [tuarua/WebViewANE#92]
hi
is this ANE allows us  to zoom mechanic using the multi touch inputs of a mobile device?

**Comment by tuarua** [comment]
iOS - yes
Android - not yet

**Comment by yooni126** [comment]
ok , thank u , I'm waiting for it

**Comment by tuarua** [comment]
What do you mean you are waiting for it ?

**Comment by yooni126** [comment]
you said not yet for Android
so i'm waiting for it :)

**Comment by yooni126** [comment]
thanks for add this option
