### ISSUE TITLE
 WebViewANESample   no support  video mp4

### ISSUE THREAD

**Issue by pgy365** [tuarua/WebViewANE#93]
Have you read the README carefully?
Yes
What version of the product are you using?
0.0.30
e.g. 0.0.27
On what operating system?
Win10
If Windows is it?
64bit
 
What steps will reproduce the problem?

I have install the WebViewANESample in win10，I found   the webview not play

\<video  controls preload="auto" autoplay="autoplay" name="media"\>
\<source src="http://www.w3school.com.cn/i/movie.mp4" type="video/mp4"/\>
Your browser does not support the video tag.
\</video\>

<img alt="@pgy365" src="https://avatars1.githubusercontent.com/u/32516780?v=4&amp;s=400&amp;u=1b16d045cbbb537b10730b5ad238f078dc0cc345">

**Comment by tuarua** [comment]
H.264, the codec used with mp4, is a licensed proprietary codec from MPEG-LA.
I am not able to build and distribute the ANE without being liable to pay them a licensing fee (it's several million $) 
Chromium Embedded Framework, which the Windows version uses, supports Google's VP9 and webm. These are royalty free codecs.

**Comment by pgy365** [comment]
I know，thanks。

**Comment by TomByrne** [comment]
Hi, is there any way for us to enable H.264 support and rebuild the ANE?

**Comment by tuarua** [comment]
Hi Tom,
You would need to recompile Chromium Embedded Framework from source and then apply that on top of CefSharp.
It's no easy task.

http://magpcss.org/ceforum/viewtopic.php?f=6&t=13515&start=40
You could look to contact @sfburke on the CefSharp gitter.
https://gitter.im/cefsharp/CefSharp

You will also need a license from MPEG-LA

**Comment by tuarua** [comment]
The other alternative is to convert your videos to VP9 + webm.
This is what Spotify and Steam do

**Comment by TomByrne** [comment]
Thanks for the quick reply.
We're trying to get Youtube live streams to show (which only use H.264).
I guess I'll have a crack at recompiling CEF.
