### ISSUE TITLE
Submitted to the AppStore error

### ISSUE THREAD

**Issue by nidiy** [tuarua/WebViewANE#94]
Hello, I am using WebViewANE to develop APP in submitting to the Apple store when prompted to error,

v0.0.32
AIR SDK 27

ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value
 'S5T2574567.com .randioo.gaming' for key 'application-identifier' in 'Payload/randioo.app/Frameworks/FreSwift.framework/FreSwift' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier."

![qq 20171011162034](https://user-images.githubusercontent.com/9928382/31429495-ce70ca2c-aea0-11e7-8f0f-3e092a7e6d72.jpg)

Commissioning and equipment can be installed normally
What should I do?

**Comment by tuarua** [comment]
Hi,
What IDE are you using to build and sign your AIR ipa?
Regarding errors 1&3.
Can you confirm that you are using production(distribution) certificates and provisioning profile and that these are configured correctly for your appId.

Error 2
Unless you are using the SwiftIOSANE (the sample project) in your app you shouldn't be packaging this framework

Error 4
I will have to look into this. Bitcode should be set to false, but it may be set to true.

**Comment by nidiy** [comment]
hi, @tuarua 
1. IDE is Mac IntelliJ IDEA 2017.2
2. The use of production (distribution) certificates and configuration files with AppID is correct because the previous version of APP has been installed on AppStore.
3. SwiftIOSANE has been removed from the project
4  Where does Bitcode need to be set up?

![qq 20171012102051](https://user-images.githubusercontent.com/9928382/31476435-e852844c-af38-11e7-9c7b-6582920a22d4.jpg)

![qq 20171012103116](https://user-images.githubusercontent.com/9928382/31476447-fa4ad99c-af38-11e7-9b52-4c9da2d19e35.jpg)

**Comment by tuarua** [comment]
I will look further into the entitlement errors - when I have access to my mac from tomorrow.
Re: bitcode - this is a setting when creating the ANE and frameworks - I need to confirm it is set to false.

**Comment by tuarua** [comment]
I have reproduced the entitlement errors you are getting.
I have added a note to the Adobe issue.
Please vote:
https://tracker.adobe.com/#/view/AIR-4198407

I will look into whether it can be resolved in the short term with a resign script.

I have found the source of the bitcode error and will upload new files shortly.

**Comment by nidiy** [comment]
OK , thank you for your support!

**Comment by tuarua** [comment]
Checkout latest.
Run /example-mobile/get_ios_dependencies.sh to pull latest FreSwift
Bitcode issue is sorted.
See instructions here https://github.com/tuarua/Adobe-AIR-Project-AppStore-Preparation for packaging for submission to AppStore

**Comment by nidiy** [comment]
thank you very much! Bitcode problem resolved.
However, I suggest the following error when referring to https://github.com/tuarua/Adobe-AIR-Project-AppStore-Preparation reloading. What is the reason?

![qq 20171016105754](https://user-images.githubusercontent.com/9928382/31593458-5c65b1da-b261-11e7-8536-4e2c5078f873.jpg)

**Comment by nidiy** [comment]
thank you very much! Bitcode problem resolved.
However, I suggest the following error when referring to https://github.com/tuarua/Adobe-AIR-Project-AppStore-Preparation reloading. What is the reason?

![qq 20171016105754](https://user-images.githubusercontent.com/9928382/31595630-b18027aa-b26f-11e7-9afe-b2eb629deef4.jpg)

**Comment by nidiy** [comment]
Thank you very much for your support and other problems are solved.

But in the use of https://github.com/tuarua/Adobe-AIR-Project-AppStore-Preparation
Follow the steps you provided to package the success, found that the signature is not AppStroe certificate signature. But in fact I was right to use the AppStroe certificate to sign the .ipa and .app.

![1](https://user-images.githubusercontent.com/9928382/31601545-ce08fdf8-b28c-11e7-924a-e303cbe93a6d.jpg)

![2](https://user-images.githubusercontent.com/9928382/31601308-0dbd8744-b28c-11e7-8d4b-d0388df4b88e.jpg)

**Comment by tuarua** [comment]
I missed an image in the README
![3](https://user-images.githubusercontent.com/12083217/31631779-b1dce7cc-b2b2-11e7-83cf-0a02dbfd2bed.png)

Make sure you have added your certificate and "Apple Worldwide Developer Certification Authority" to your keychain - see instructions here.
https://stackoverflow.com/questions/31711335/ios-missing-or-invalid-signature-the-bundle-is-not-signed-using-an-apple-submis

I have successfully verified my app.

**There is 1 more step to include Swift libraries. I will add further instructions.**

**Comment by tuarua** [comment]
I am working on a more reliable script. I will update when it is ready.

**Comment by tuarua** [comment]
Please see 
https://github.com/tuarua/WebViewANE/tree/master/example-mobile/package_for_ios_appstore

Simple single script to prepare the correct ipa.
I have run this and successfully passed App Store submission.

**Comment by nidiy** [comment]
Too holding! Thank you, I'm ready to try it.

**Comment by nidiy** [comment]
Ask for help,
    Hello, I configured the. Sh file to run wrong, what is this reason?

Also: README.md in your project WebViewANE
In the "README here" point to the link is wrong
![qq 20171019100349](https://user-images.githubusercontent.com/9928382/31751039-0fa8a9ea-b4b6-11e7-896d-e3de20651fb5.jpg)
![qq 20171019100356](https://user-images.githubusercontent.com/9928382/31751046-13fe1f3e-b4b6-11e7-9d05-237a9a228025.jpg)

**Comment by tuarua** [comment]
try using:      ./resign.shinstead of:     bash resign.sh 
bash may be setup differently on my machine

**Comment by nidiy** [comment]
the same mistake.

**Comment by nidiy** [comment]
hi, Trying on both Macs are the same mistakes. Is it necessary to configure a special system environment?

**Comment by tuarua** [comment]
I can use any of the following
/bin/bash resign.sh
bash resign.sh
./resign.sh

So please check you have bash is setup correctly
http://www.macdevcenter.com/pub/a/mac/2004/02/24/bash.html

You should use internet search to help resolve issues like this.
I can't provide support for every little thing.

**Comment by nidiy** [comment]
hi,
My question has been solved.
    Sorry, this is my own mistake, because I edited the resign.sh script on Winows cause resign.sh on the Mac to increase the number of ^ M characters, so it can not run properly, use the name vi -b resign .sh can see, just use the vim editor to remove ^ M on it
![qq 20171025141747](https://user-images.githubusercontent.com/9928382/31983666-be566ba6-b990-11e7-90b4-503380cc966f.png)

**Comment by nidiy** [comment]
Has been successfully submitted to the AppStroe audit, thank you very much for your help.

**Comment by tuarua** [comment]
That's good news! You're welcome.
Yes, Windows can modify encodings.
