### ISSUE TITLE
M

### ISSUE THREAD

**Issue by marinlines** [tuarua/WebViewANE#95]
- **Have you read the README carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
e.g. 0.0.27

- **On what operating system?**
    - OSX, Win7, Win 8, Win10, etc?
    
- **If Windows is it?**
    - 32bit or 64bit

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?

- **Which version of AIR are you using?**
    - 19,20.. etc?

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**

**Comment by tuarua** [comment]
?
