### ISSUE TITLE
Empty result - (High Sierra enforces https only)

### ISSUE THREAD

**Issue by hferreira** [tuarua/WebViewANE#97]
Tested on macOS + IntelliJ + AIR 27 + Flex.

Test Code:

                var settings:Settings = new Settings();
                settings.popup.behaviour = Behaviour.NEW_WINDOW;
                settings.popup.dimensions.width = 500;
                settings.popup.dimensions.height = 500;
 
                var viewPort:Rectangle = new Rectangle(90, 90, 500, 500);
                var webView:WebViewANE = new WebViewANE();
                webView.init(stage, viewPort, "http://www.youtube.com", settings, 1.0, 0xF1F1F1, 1.0);
                webView.load("http://www.google.pt");
                webView.focus();
                webView.visible = true;
Result:
Empty rectangle !

**Comment by tuarua** [comment]
You say you are using Flex. Are you initing the webView in the addedToStage event ?
If you init it too early then there is no native view to attach it too.

Also you shouldn't use webView.load("http://www.google.pt"); to load your initial url.

Set your initial url in .init  eg webView.init(stage, viewPort, "http://www.google.pt", settings, 1.0, 0xF1F1F1, 1.0);

**Comment by hferreira** [comment]
Hello,

I thought about that.
This test code exists on a button click event !

The load it's just a test.

**Comment by tuarua** [comment]
What version of OSX, the latest 10.13 ?

Can you run the provided example or in your own can you add these events.
It will determine if the view is not being added or if the page is loading or not.

webView.addEventListener(WebViewEvent.ON_PROPERTY_CHANGE, onPropertyChange);
webView.addEventListener(WebViewEvent.ON_FAIL, onFail);

**Comment by hferreira** [comment]
Only ON_PROPERTY_CHANGE is fired many times.
First result is:
propertyName = "estimatedTime"
tab = 0
value = 0.1

**Comment by tuarua** [comment]
Can you upload a simple project I can use to test somewhere.

**Comment by hferreira** [comment]
Sample (isolated) case:
<?xml version="1.0"?>
<s:WindowedApplication xmlns:fx="http://ns.adobe.com/mxml/2009"
                       xmlns:s="library://ns.adobe.com/flex/spark"
                       backgroundColor="green"
                       creationComplete="this.maximize()">
    <fx:Script>
        <![CDATA[
            import com.tuarua.CommonDependencies;
            import com.tuarua.WebViewANE;
            import com.tuarua.webview.Settings;
            import com.tuarua.webview.popup.Behaviour;

            private var commonDependenciesANE:CommonDependencies = new CommonDependencies();

            private function openWebView():void
            {
                var settings:Settings = new Settings();
                settings.popup.behaviour = Behaviour.NEW_WINDOW;
                settings.popup.dimensions.width = 500;
                settings.popup.dimensions.height = 500;

                var viewPort:Rectangle = new Rectangle(20, 20, 500, 500);
                var webView:WebViewANE = new WebViewANE();
                webView.init(stage, viewPort, "http://www.youtube.com", settings, 1.0, 0xF1F1F1, 1.0);
                webView.focus();
                webView.visible = true;
            }
        ]]></fx:Script>
    <s:Button click="openWebView()"
              label="Test WebView ANE"/>
</s:WindowedApplication>

Full source code ready to run available here: [TuaRuaWebView.zip](https://github.com/tuarua/WebViewANE/files/1389305/TuaRuaWebView.zip)

**Comment by hferreira** [comment]
I already tried that with the same result.
Perhaps no one uses your ANE with Flex.

**Comment by tuarua** [comment]
They do.

**Comment by tuarua** [comment]
This is related to High Sierra.
https urls **must** be used
