### ISSUE TITLE
Does not work with CommonDependencies from DesktopToastANE

### ISSUE THREAD

**Issue by hferreira** [tuarua/WebViewANE#98]
With CommonDependencies from DesktopToastANE I get the following error:

ArgumentError: Error #3500: The extension context does not have a method with the name init.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.tuarua::WebViewANE/init()[D:\dev\flash\WebViewANE\native_extension\src\com\tuarua\WebViewANE.as:462]

**Comment by tuarua** [comment]
Looks like there's a version mismatch - the toast ane version is outdated.
I will sort that out tomorrow

**Comment by tuarua** [comment]
I've uploaded latest CommonDependencies.ane to DesktopToastANE project

**Comment by hferreira** [comment]
Thanks
